import { z } from 'zod';
import { IdSchema } from './primitives.js';

// File names are generated by the image pipeline (`<name>-<width>.<fmt>`), never
// user-controlled, so this constrains them to a safe charset for use in paths
// and URL segments. No slashes, dots-only at the extension.
const FileNameSchema = z
  .string()
  .min(1)
  .max(255)
  .regex(/^[A-Za-z0-9_-]+\.(avif|webp|jpg)$/, 'unexpected variant file name');

/** One generated variant file (one format at one width). */
export const MediaVariantSchema = z.object({
  format: z.enum(['avif', 'webp']),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  path: FileNameSchema,
});
export type MediaVariant = z.infer<typeof MediaVariantSchema>;

/**
 * An uploaded, optimized media asset. The binary variants live on disk under the
 * project's media root; this record is the tenant-scoped metadata (stored as a
 * `media` content row) that the editor and renderer reference.
 */
export const MediaAssetSchema = z.object({
  id: IdSchema,
  /** Original upload file name (for display only). */
  filename: z.string().min(1).max(255),
  /** Detected source format (sharp), e.g. `png`, `jpeg`. */
  format: z.string().min(1).max(20),
  bytes: z.number().int().nonnegative(),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  alt: z.string().max(500).optional(),
  /** Tiny blurred inline LQIP data URI. */
  placeholder: z.string().max(20_000).optional(),
  variants: z.array(MediaVariantSchema).max(50),
  /** Fallback JPEG file name (for the plain `<img>` src). */
  fallback: FileNameSchema,
  /** Root-relative URL of the fallback image (what an Image block's `src` stores). */
  url: z
    .string()
    .min(1)
    .max(2048)
    .regex(/^\/media\/[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+\.(avif|webp|jpg)$/),
});
export type MediaAsset = z.infer<typeof MediaAssetSchema>;
