// The AUTHORED half of the Tailwind reference: one entry per CSS-property signature, giving it a
// category, a human title, a sentence of prose, and a preview kind.
//
// Written for this project. Tailwind's own documentation prose is NOT covered by the MIT licence on
// the `tailwindcss` npm package (tailwindcss.com is a separate, unlicensed repository), so none of it
// is copied here — only the mechanically-derived facts in `generated.ts` come from the package.
//
// Every signature the generator emits MUST have an entry here, and every entry here must correspond
// to a real signature — `test/topics.test.ts` fails on either gap. That is what stops a Tailwind
// upgrade from quietly introducing an untitled topic, or leaving a stale one behind.
//
// Keys are the property signature: the utility's generated CSS properties, deduped, comma-joined, in
// declaration order. That key is why the topic list is derived rather than curated — `text-sm`
// generates `font-size,line-height` and `text-red-500` generates `color`, so the polymorphic `text-`
// root splits into "Font Size" and "Text Color" without anyone deciding it should.
import type { TopicDoc } from './types.js';

export const TOPIC_DOCS: Record<string, TopicDoc> = {
  // ── Layout ────────────────────────────────────────────────────────────────────────────────────
  display: { category: 'layout', title: 'Display', description: 'Sets the box type an element generates — block, inline, flex, grid, or none to remove it from the layout entirely.', preview: 'none' },
  position: { category: 'layout', title: 'Position', description: 'Chooses how an element is placed: in normal flow, offset from it, or taken out of it and positioned against an ancestor or the viewport.', preview: 'none' },
  inset: { category: 'layout', title: 'Inset', description: 'Offsets a positioned element from all four edges of its containing block at once.', preview: 'size' },
  'inset-inline': { category: 'layout', title: 'Inset Horizontal', description: 'Offsets a positioned element from both inline (left and right in LTR) edges of its containing block.', preview: 'size' },
  'inset-block': { category: 'layout', title: 'Inset Vertical', description: 'Offsets a positioned element from both block (top and bottom) edges of its containing block.', preview: 'size' },
  top: { category: 'layout', title: 'Top', description: 'Offsets a positioned element from the top edge of its containing block.', preview: 'size' },
  right: { category: 'layout', title: 'Right', description: 'Offsets a positioned element from the right edge of its containing block.', preview: 'size' },
  bottom: { category: 'layout', title: 'Bottom', description: 'Offsets a positioned element from the bottom edge of its containing block.', preview: 'size' },
  left: { category: 'layout', title: 'Left', description: 'Offsets a positioned element from the left edge of its containing block.', preview: 'size' },
  'inset-inline-start': { category: 'layout', title: 'Inset Inline Start', description: 'Offsets a positioned element from the start of the inline axis — the left edge in LTR, the right in RTL.', preview: 'size' },
  'inset-inline-end': { category: 'layout', title: 'Inset Inline End', description: 'Offsets a positioned element from the end of the inline axis — the right edge in LTR, the left in RTL.', preview: 'size' },
  'inset-block-start': { category: 'layout', title: 'Inset Block Start', description: 'Offsets a positioned element from the start of the block axis (the top, in horizontal writing modes).', preview: 'size' },
  'inset-block-end': { category: 'layout', title: 'Inset Block End', description: 'Offsets a positioned element from the end of the block axis (the bottom, in horizontal writing modes).', preview: 'size' },
  'z-index': { category: 'layout', title: 'Z-Index', description: 'Sets the stacking order of a positioned element against its siblings — higher values paint on top.', preview: 'none' },
  float: { category: 'layout', title: 'Float', description: 'Takes an element out of normal flow and pushes it to one side, letting text wrap around it.', preview: 'none' },
  clear: { category: 'layout', title: 'Clear', description: 'Pushes an element below any preceding floated elements instead of letting it sit alongside them.', preview: 'none' },
  isolation: { category: 'layout', title: 'Isolation', description: 'Forces an element to create its own stacking context, so blend modes inside it cannot reach the content behind it.', preview: 'none' },
  visibility: { category: 'layout', title: 'Visibility', description: 'Hides an element while it keeps occupying its space in the layout (unlike `hidden`, which removes the box).', preview: 'none' },
  'object-fit': { category: 'layout', title: 'Object Fit', description: 'Decides how a replaced element — an image or video — is resized to fill its box: cropped, letterboxed, or stretched.', preview: 'none' },
  'object-position': { category: 'layout', title: 'Object Position', description: 'Chooses which part of an image or video stays visible when `object-fit` crops it.', preview: 'none' },
  overflow: { category: 'layout', title: 'Overflow', description: 'Controls what happens to content that exceeds its box on both axes — clip it, scroll it, or let it spill.', preview: 'none' },
  'overflow-x': { category: 'layout', title: 'Overflow Horizontal', description: 'Controls what happens to content that exceeds its box horizontally.', preview: 'none' },
  'overflow-y': { category: 'layout', title: 'Overflow Vertical', description: 'Controls what happens to content that exceeds its box vertically.', preview: 'none' },
  'overscroll-behavior': { category: 'layout', title: 'Overscroll Behavior', description: 'Stops a scroll that reaches the end of this element from chaining to the page behind it, and can disable bounce.', preview: 'none' },
  'overscroll-behavior-x': { category: 'layout', title: 'Overscroll Behavior Horizontal', description: 'Controls scroll chaining and bounce when a horizontal scroll reaches this element’s end.', preview: 'none' },
  'overscroll-behavior-y': { category: 'layout', title: 'Overscroll Behavior Vertical', description: 'Controls scroll chaining and bounce when a vertical scroll reaches this element’s end.', preview: 'none' },
  'aspect-ratio': { category: 'layout', title: 'Aspect Ratio', description: 'Locks a box to a proportion, so its height follows from its width — useful for media that must not shift the layout while loading.', preview: 'none' },
  columns: { category: 'layout', title: 'Columns', description: 'Flows content into a multi-column layout, by column count or by ideal column width.', preview: 'none' },
  'break-after': { category: 'layout', title: 'Break After', description: 'Forces or forbids a column or page break immediately after an element.', preview: 'none' },
  'break-before': { category: 'layout', title: 'Break Before', description: 'Forces or forbids a column or page break immediately before an element.', preview: 'none' },
  'break-inside': { category: 'layout', title: 'Break Inside', description: 'Keeps an element from being split across a column or page boundary.', preview: 'none' },
  '-webkit-box-decoration-break,box-decoration-break': { category: 'layout', title: 'Box Decoration Break', description: 'Decides whether backgrounds, borders and padding are drawn once around a fragmented element or repeated on each fragment.', preview: 'none' },
  'box-sizing': { category: 'layout', title: 'Box Sizing', description: 'Chooses whether an element’s declared width and height include its padding and border, or sit inside them.', preview: 'none' },
  'width,max-width': { category: 'layout', title: 'Container', description: 'A responsive fixed-width wrapper that steps up to match each breakpoint, keeping page content off the screen edges.', preview: 'none' },
  'container-type': { category: 'layout', title: 'Container Type', description: 'Marks an element as a query container, so its descendants can style themselves against ITS width rather than the viewport’s.', preview: 'none' },
  contain: { category: 'layout', title: 'Contain', description: 'Promises the browser that an element’s layout, style or paint cannot affect the rest of the page, letting it skip work.', preview: 'none' },

  // ── Flexbox & Grid ────────────────────────────────────────────────────────────────────────────
  'flex-basis': { category: 'flexbox-grid', title: 'Flex Basis', description: 'Sets a flex item’s starting size before free space is distributed.', preview: 'size' },
  'flex-direction': { category: 'flexbox-grid', title: 'Flex Direction', description: 'Sets the main axis of a flex container — row or column, forwards or reversed.', preview: 'none' },
  'flex-wrap': { category: 'flexbox-grid', title: 'Flex Wrap', description: 'Decides whether flex items are forced onto one line or allowed to wrap onto several.', preview: 'none' },
  flex: { category: 'flexbox-grid', title: 'Flex', description: 'The shorthand for how a flex item grows, shrinks and starts — the usual way to say "take one share of the space".', preview: 'none' },
  'flex-grow': { category: 'flexbox-grid', title: 'Flex Grow', description: 'Sets whether a flex item expands to absorb leftover space on the main axis.', preview: 'none' },
  'flex-shrink': { category: 'flexbox-grid', title: 'Flex Shrink', description: 'Sets whether a flex item is allowed to shrink below its basis when space runs short.', preview: 'none' },
  order: { category: 'flexbox-grid', title: 'Order', description: 'Reorders a flex or grid item visually without changing the source order that assistive technology reads.', preview: 'none' },
  'grid-template-columns': { category: 'flexbox-grid', title: 'Grid Template Columns', description: 'Defines the column tracks of a grid.', preview: 'none' },
  'grid-template-rows': { category: 'flexbox-grid', title: 'Grid Template Rows', description: 'Defines the row tracks of a grid.', preview: 'none' },
  'grid-column': { category: 'flexbox-grid', title: 'Grid Column Span', description: 'Sets how many column tracks a grid item spans.', preview: 'none' },
  'grid-column-start': { category: 'flexbox-grid', title: 'Grid Column Start', description: 'Pins a grid item to a starting column line.', preview: 'none' },
  'grid-column-end': { category: 'flexbox-grid', title: 'Grid Column End', description: 'Pins a grid item to an ending column line.', preview: 'none' },
  'grid-row': { category: 'flexbox-grid', title: 'Grid Row Span', description: 'Sets how many row tracks a grid item spans.', preview: 'none' },
  'grid-row-start': { category: 'flexbox-grid', title: 'Grid Row Start', description: 'Pins a grid item to a starting row line.', preview: 'none' },
  'grid-row-end': { category: 'flexbox-grid', title: 'Grid Row End', description: 'Pins a grid item to an ending row line.', preview: 'none' },
  'grid-auto-flow': { category: 'flexbox-grid', title: 'Grid Auto Flow', description: 'Controls how items the grid places automatically are filled in — by row, by column, and whether gaps get backfilled.', preview: 'none' },
  'grid-auto-columns': { category: 'flexbox-grid', title: 'Grid Auto Columns', description: 'Sizes the column tracks the grid creates implicitly for items placed outside the explicit template.', preview: 'none' },
  'grid-auto-rows': { category: 'flexbox-grid', title: 'Grid Auto Rows', description: 'Sizes the row tracks the grid creates implicitly for items placed outside the explicit template.', preview: 'none' },
  gap: { category: 'flexbox-grid', title: 'Gap', description: 'Sets the gutter between rows and columns of a flex or grid container — spacing without margins on the children.', preview: 'size' },
  'column-gap': { category: 'flexbox-grid', title: 'Column Gap', description: 'Sets the gutter between columns of a flex or grid container.', preview: 'size' },
  'row-gap': { category: 'flexbox-grid', title: 'Row Gap', description: 'Sets the gutter between rows of a flex or grid container.', preview: 'size' },
  'justify-content': { category: 'flexbox-grid', title: 'Justify Content', description: 'Distributes flex or grid items along the main axis, and shares out any leftover space between them.', preview: 'none' },
  'justify-items': { category: 'flexbox-grid', title: 'Justify Items', description: 'Aligns every grid item within its own track along the inline axis.', preview: 'none' },
  'justify-self': { category: 'flexbox-grid', title: 'Justify Self', description: 'Overrides the container’s inline-axis alignment for a single item.', preview: 'none' },
  'align-content': { category: 'flexbox-grid', title: 'Align Content', description: 'Distributes the ROWS of a wrapped flex container or a grid along the cross axis.', preview: 'none' },
  'align-items': { category: 'flexbox-grid', title: 'Align Items', description: 'Aligns every item within its line along the cross axis — the utility that vertically centres a row.', preview: 'none' },
  'align-self': { category: 'flexbox-grid', title: 'Align Self', description: 'Overrides the container’s cross-axis alignment for a single item.', preview: 'none' },
  'place-content': { category: 'flexbox-grid', title: 'Place Content', description: 'Sets `align-content` and `justify-content` together.', preview: 'none' },
  'place-items': { category: 'flexbox-grid', title: 'Place Items', description: 'Sets `align-items` and `justify-items` together — `place-items-center` centres grid children on both axes.', preview: 'none' },
  'place-self': { category: 'flexbox-grid', title: 'Place Self', description: 'Sets `align-self` and `justify-self` together for a single item.', preview: 'none' },

  // ── Spacing ───────────────────────────────────────────────────────────────────────────────────
  padding: { category: 'spacing', title: 'Padding', description: 'Adds space inside an element on all four sides, between its content and its border.', preview: 'size' },
  'padding-inline': { category: 'spacing', title: 'Horizontal Padding', description: 'Adds space inside an element on its left and right (inline) sides.', preview: 'size' },
  'padding-block': { category: 'spacing', title: 'Vertical Padding', description: 'Adds space inside an element on its top and bottom (block) sides.', preview: 'size' },
  'padding-top': { category: 'spacing', title: 'Padding Top', description: 'Adds space inside an element above its content.', preview: 'size' },
  'padding-right': { category: 'spacing', title: 'Padding Right', description: 'Adds space inside an element to the right of its content.', preview: 'size' },
  'padding-bottom': { category: 'spacing', title: 'Padding Bottom', description: 'Adds space inside an element below its content.', preview: 'size' },
  'padding-left': { category: 'spacing', title: 'Padding Left', description: 'Adds space inside an element to the left of its content.', preview: 'size' },
  'padding-inline-start': { category: 'spacing', title: 'Padding Inline Start', description: 'Adds inside space at the start of the inline axis — the left in LTR, the right in RTL.', preview: 'size' },
  'padding-inline-end': { category: 'spacing', title: 'Padding Inline End', description: 'Adds inside space at the end of the inline axis — the right in LTR, the left in RTL.', preview: 'size' },
  'padding-block-start': { category: 'spacing', title: 'Padding Block Start', description: 'Adds inside space at the start of the block axis (the top, in horizontal writing modes).', preview: 'size' },
  'padding-block-end': { category: 'spacing', title: 'Padding Block End', description: 'Adds inside space at the end of the block axis (the bottom, in horizontal writing modes).', preview: 'size' },
  margin: { category: 'spacing', title: 'Margin', description: 'Adds space outside an element on all four sides. Negative values pull neighbours closer.', preview: 'size' },
  'margin-inline': { category: 'spacing', title: 'Horizontal Margin', description: 'Adds space outside an element on its left and right — `mx-auto` is how a fixed-width block gets centred.', preview: 'size' },
  'margin-block': { category: 'spacing', title: 'Vertical Margin', description: 'Adds space outside an element on its top and bottom.', preview: 'size' },
  'margin-top': { category: 'spacing', title: 'Margin Top', description: 'Adds space above an element.', preview: 'size' },
  'margin-right': { category: 'spacing', title: 'Margin Right', description: 'Adds space to the right of an element.', preview: 'size' },
  'margin-bottom': { category: 'spacing', title: 'Margin Bottom', description: 'Adds space below an element.', preview: 'size' },
  'margin-left': { category: 'spacing', title: 'Margin Left', description: 'Adds space to the left of an element.', preview: 'size' },
  'margin-inline-start': { category: 'spacing', title: 'Margin Inline Start', description: 'Adds outside space at the start of the inline axis — the left in LTR, the right in RTL.', preview: 'size' },
  'margin-inline-end': { category: 'spacing', title: 'Margin Inline End', description: 'Adds outside space at the end of the inline axis — the right in LTR, the left in RTL.', preview: 'size' },
  'margin-block-start': { category: 'spacing', title: 'Margin Block Start', description: 'Adds outside space at the start of the block axis (the top, in horizontal writing modes).', preview: 'size' },
  'margin-block-end': { category: 'spacing', title: 'Margin Block End', description: 'Adds outside space at the end of the block axis (the bottom, in horizontal writing modes).', preview: 'size' },
  'margin-inline-start,margin-inline-end': { category: 'spacing', title: 'Horizontal Space Between', description: 'Puts a gap between an element’s children by margining all but the first — for a row of siblings you do not control individually.', preview: 'size' },
  'margin-block-start,margin-block-end': { category: 'spacing', title: 'Vertical Space Between', description: 'Puts a gap between an element’s stacked children by margining all but the first.', preview: 'size' },
  '--tw-space-x-reverse': { category: 'spacing', title: 'Horizontal Space Reverse', description: 'Flips which side the horizontal space-between margin lands on, for a row rendered in reverse order.', preview: 'none' },
  '--tw-space-y-reverse': { category: 'spacing', title: 'Vertical Space Reverse', description: 'Flips which side the vertical space-between margin lands on, for a column rendered in reverse order.', preview: 'none' },

  // ── Sizing ────────────────────────────────────────────────────────────────────────────────────
  width: { category: 'sizing', title: 'Width', description: 'Sets an element’s width — from the spacing scale, a fraction of its parent, or a viewport unit.', preview: 'size' },
  'min-width': { category: 'sizing', title: 'Min Width', description: 'Sets a floor below which an element will not shrink. `min-w-0` is the usual fix for a flex child that refuses to truncate.', preview: 'size' },
  'max-width': { category: 'sizing', title: 'Max Width', description: 'Sets a ceiling above which an element will not grow — the usual way to cap a text column for readability.', preview: 'size' },
  height: { category: 'sizing', title: 'Height', description: 'Sets an element’s height.', preview: 'size' },
  'min-height': { category: 'sizing', title: 'Min Height', description: 'Sets a floor below which an element will not shrink vertically — `min-h-screen` for a full-viewport section.', preview: 'size' },
  'max-height': { category: 'sizing', title: 'Max Height', description: 'Sets a ceiling above which an element will not grow vertically.', preview: 'size' },
  'width,height': { category: 'sizing', title: 'Size', description: 'Sets width and height together — the shorthand for square boxes like icons and avatars.', preview: 'size' },
  'inline-size': { category: 'sizing', title: 'Inline Size', description: 'Sets the size along the inline axis — width in horizontal writing modes, height in vertical ones.', preview: 'size' },
  'min-inline-size': { category: 'sizing', title: 'Min Inline Size', description: 'Sets a floor for the inline-axis size, in writing-mode-relative terms.', preview: 'size' },
  'max-inline-size': { category: 'sizing', title: 'Max Inline Size', description: 'Sets a ceiling for the inline-axis size, in writing-mode-relative terms.', preview: 'size' },
  'block-size': { category: 'sizing', title: 'Block Size', description: 'Sets the size along the block axis — height in horizontal writing modes, width in vertical ones.', preview: 'size' },
  'min-block-size': { category: 'sizing', title: 'Min Block Size', description: 'Sets a floor for the block-axis size, in writing-mode-relative terms.', preview: 'size' },
  'max-block-size': { category: 'sizing', title: 'Max Block Size', description: 'Sets a ceiling for the block-axis size, in writing-mode-relative terms.', preview: 'size' },

  // ── Typography ────────────────────────────────────────────────────────────────────────────────
  'font-family': { category: 'typography', title: 'Font Family', description: 'Picks a font stack. A project’s brand fonts appear here as extra utilities once they are set in Settings → Typography.', preview: 'text' },
  'font-size,line-height': { category: 'typography', title: 'Font Size', description: 'Sets the type size, each step carrying a matching default line height you can override with a modifier like `text-sm/relaxed`.', preview: 'text' },
  'font-weight': { category: 'typography', title: 'Font Weight', description: 'Sets the stroke weight of the type. A variable font honours every step; a static one snaps to the weights it actually ships.', preview: 'text' },
  'font-style': { category: 'typography', title: 'Font Style', description: 'Turns italics on or off.', preview: 'text' },
  'font-stretch': { category: 'typography', title: 'Font Stretch', description: 'Selects a narrower or wider face — only visible on fonts that carry a width axis.', preview: 'text' },
  'font-variant-numeric': { category: 'typography', title: 'Font Variant Numeric', description: 'Switches on alternate figure styles: tabular figures that align in columns, old-style figures, fractions, ordinals.', preview: 'text' },
  '-webkit-font-smoothing,-moz-osx-font-smoothing': { category: 'typography', title: 'Font Smoothing', description: 'Chooses subpixel or greyscale antialiasing — light text on a dark background often looks less heavy antialiased.', preview: 'text' },
  'line-height': { category: 'typography', title: 'Line Height', description: 'Sets leading independently of the type size.', preview: 'text' },
  'letter-spacing': { category: 'typography', title: 'Letter Spacing', description: 'Tightens or loosens the tracking between characters — large display type usually wants a little negative tracking.', preview: 'text' },
  color: { category: 'typography', title: 'Text Color', description: 'Sets the text colour, which is also what `currentColor` resolves to for borders and inline SVG.', preview: 'color' },
  'text-align': { category: 'typography', title: 'Text Align', description: 'Aligns text within its box.', preview: 'text' },
  'text-transform': { category: 'typography', title: 'Text Transform', description: 'Changes the rendered case of the text without changing the underlying content.', preview: 'text' },
  'text-decoration-line': { category: 'typography', title: 'Text Decoration', description: 'Adds or removes an underline, overline or strike-through.', preview: 'text' },
  'text-decoration-color': { category: 'typography', title: 'Text Decoration Color', description: 'Colours the underline or strike-through independently of the text.', preview: 'color' },
  'text-decoration-style': { category: 'typography', title: 'Text Decoration Style', description: 'Draws the underline solid, dashed, dotted, doubled or wavy.', preview: 'text' },
  'text-decoration-thickness': { category: 'typography', title: 'Text Decoration Thickness', description: 'Sets how heavy the underline or strike-through is drawn.', preview: 'text' },
  'text-underline-offset': { category: 'typography', title: 'Text Underline Offset', description: 'Moves the underline away from the baseline, so it stops colliding with descenders.', preview: 'text' },
  'text-indent': { category: 'typography', title: 'Text Indent', description: 'Indents the first line of a block of text. Negative values give a hanging indent.', preview: 'size' },
  'text-overflow': { category: 'typography', title: 'Text Overflow', description: 'Chooses whether text that overflows is clipped flat or ends in an ellipsis.', preview: 'none' },
  'overflow,text-overflow,white-space': { category: 'typography', title: 'Truncate', description: 'The one-liner for a single line of text that must not wrap: no wrapping, hidden overflow, trailing ellipsis.', preview: 'none' },
  'overflow,display,-webkit-box-orient,-webkit-line-clamp': { category: 'typography', title: 'Line Clamp', description: 'Limits text to a fixed number of lines and ends the last one with an ellipsis.', preview: 'none' },
  'text-wrap': { category: 'typography', title: 'Text Wrap', description: 'Tunes how lines break — `text-balance` evens out a short heading, `text-pretty` avoids leaving one word alone on the last line.', preview: 'none' },
  'white-space': { category: 'typography', title: 'Whitespace', description: 'Controls whether whitespace collapses and whether text is allowed to wrap.', preview: 'none' },
  'word-break': { category: 'typography', title: 'Word Break', description: 'Allows breaking inside a word, or forbids it for languages where that would be wrong.', preview: 'none' },
  'overflow-wrap': { category: 'typography', title: 'Overflow Wrap', description: 'Lets an unbreakably long string — a URL, a hash — wrap rather than blow out its container.', preview: 'none' },
  'overflow-wrap,word-break': { category: 'typography', title: 'Break Normal', description: 'Restores the default word-breaking behaviour, undoing a break utility applied further up.', preview: 'none' },
  '-webkit-hyphens,hyphens': { category: 'typography', title: 'Hyphens', description: 'Enables automatic hyphenation, or forces it only where a soft hyphen was authored.', preview: 'none' },
  'vertical-align': { category: 'typography', title: 'Vertical Align', description: 'Aligns an inline or table-cell element against the surrounding line box.', preview: 'none' },
  'list-style-type': { category: 'typography', title: 'List Style Type', description: 'Chooses the list marker — disc, decimal, or none.', preview: 'none' },
  'list-style-position': { category: 'typography', title: 'List Style Position', description: 'Places the list marker inside the content box or hanging outside it.', preview: 'none' },
  'list-style-image': { category: 'typography', title: 'List Style Image', description: 'Removes a custom image marker, restoring the plain list marker.', preview: 'none' },
  'tab-size': { category: 'typography', title: 'Tab Size', description: 'Sets how many spaces a tab character occupies in preformatted text.', preview: 'none' },
  content: { category: 'typography', title: 'Content', description: 'Clears the generated content of a `::before` or `::after` pseudo-element.', preview: 'none' },

  // ── Backgrounds ───────────────────────────────────────────────────────────────────────────────
  'background-color': { category: 'backgrounds', title: 'Background Color', description: 'Fills an element’s background. A project’s brand colours appear here as extra utilities once they are set in Settings.', preview: 'color' },
  'background-image': { category: 'backgrounds', title: 'Background Image', description: 'Paints a gradient — linear, radial or conic — as the background layer. Pair with the from/via/to colour stops.', preview: 'box' },
  '--tw-gradient-from,--tw-gradient-stops': { category: 'backgrounds', title: 'Gradient From Color', description: 'Sets the starting colour stop of a gradient background.', preview: 'color' },
  '--tw-gradient-via,--tw-gradient-via-stops,--tw-gradient-stops': { category: 'backgrounds', title: 'Gradient Via Color', description: 'Sets a middle colour stop, turning a two-stop gradient into a three-stop one.', preview: 'color' },
  '--tw-gradient-to,--tw-gradient-stops': { category: 'backgrounds', title: 'Gradient To Color', description: 'Sets the ending colour stop of a gradient background.', preview: 'color' },
  '--tw-gradient-from-position': { category: 'backgrounds', title: 'Gradient From Position', description: 'Moves the starting stop along the gradient line, compressing or delaying the transition.', preview: 'none' },
  '--tw-gradient-via-position': { category: 'backgrounds', title: 'Gradient Via Position', description: 'Moves the middle stop along the gradient line.', preview: 'none' },
  '--tw-gradient-to-position': { category: 'backgrounds', title: 'Gradient To Position', description: 'Moves the ending stop along the gradient line.', preview: 'none' },
  '--tw-gradient-via-stops': { category: 'backgrounds', title: 'Gradient Via None', description: 'Drops the middle stop, returning a three-stop gradient to a plain two-stop one.', preview: 'none' },
  'background-position': { category: 'backgrounds', title: 'Background Position', description: 'Anchors the background image to an edge or corner of the box.', preview: 'none' },
  'background-size': { category: 'backgrounds', title: 'Background Size', description: 'Scales the background image to cover the box, fit inside it, or keep its own size.', preview: 'none' },
  'background-repeat': { category: 'backgrounds', title: 'Background Repeat', description: 'Controls whether and how the background image tiles.', preview: 'none' },
  'background-attachment': { category: 'backgrounds', title: 'Background Attachment', description: 'Decides whether the background scrolls with the content or stays fixed to the viewport.', preview: 'none' },
  'background-origin': { category: 'backgrounds', title: 'Background Origin', description: 'Chooses which box — border, padding or content — the background image is positioned against.', preview: 'none' },
  'background-clip': { category: 'backgrounds', title: 'Background Clip', description: 'Chooses how far the background paints. `bg-clip-text` is what makes gradient-filled headings possible.', preview: 'none' },
  'background-blend-mode': { category: 'backgrounds', title: 'Background Blend Mode', description: 'Blends an element’s background layers into each other.', preview: 'none' },

  // ── Borders ───────────────────────────────────────────────────────────────────────────────────
  'border-radius': { category: 'borders', title: 'Border Radius', description: 'Rounds all four corners of an element.', preview: 'box' },
  'border-top-left-radius,border-top-right-radius': { category: 'borders', title: 'Border Radius Top', description: 'Rounds the two top corners.', preview: 'box' },
  'border-bottom-right-radius,border-bottom-left-radius': { category: 'borders', title: 'Border Radius Bottom', description: 'Rounds the two bottom corners.', preview: 'box' },
  'border-top-left-radius,border-bottom-left-radius': { category: 'borders', title: 'Border Radius Left', description: 'Rounds the two left corners.', preview: 'box' },
  'border-top-right-radius,border-bottom-right-radius': { category: 'borders', title: 'Border Radius Right', description: 'Rounds the two right corners.', preview: 'box' },
  'border-start-start-radius,border-end-start-radius': { category: 'borders', title: 'Border Radius Inline Start', description: 'Rounds the two corners at the start of the inline axis, following the writing direction.', preview: 'box' },
  'border-start-end-radius,border-end-end-radius': { category: 'borders', title: 'Border Radius Inline End', description: 'Rounds the two corners at the end of the inline axis, following the writing direction.', preview: 'box' },
  'border-top-left-radius': { category: 'borders', title: 'Border Radius Top Left', description: 'Rounds the top-left corner only.', preview: 'box' },
  'border-top-right-radius': { category: 'borders', title: 'Border Radius Top Right', description: 'Rounds the top-right corner only.', preview: 'box' },
  'border-bottom-left-radius': { category: 'borders', title: 'Border Radius Bottom Left', description: 'Rounds the bottom-left corner only.', preview: 'box' },
  'border-bottom-right-radius': { category: 'borders', title: 'Border Radius Bottom Right', description: 'Rounds the bottom-right corner only.', preview: 'box' },
  'border-start-start-radius': { category: 'borders', title: 'Border Radius Start Start', description: 'Rounds the logical start-start corner, following the writing direction.', preview: 'box' },
  'border-start-end-radius': { category: 'borders', title: 'Border Radius Start End', description: 'Rounds the logical start-end corner, following the writing direction.', preview: 'box' },
  'border-end-start-radius': { category: 'borders', title: 'Border Radius End Start', description: 'Rounds the logical end-start corner, following the writing direction.', preview: 'box' },
  'border-end-end-radius': { category: 'borders', title: 'Border Radius End End', description: 'Rounds the logical end-end corner, following the writing direction.', preview: 'box' },
  'border-style,border-width': { category: 'borders', title: 'Border Width', description: 'Draws a border on all four sides. The bare `border` is a hairline; the numbered steps are thicker.', preview: 'box' },
  'border-inline-style,border-inline-width': { category: 'borders', title: 'Border Width Horizontal', description: 'Draws a border on the left and right sides.', preview: 'box' },
  'border-block-style,border-block-width': { category: 'borders', title: 'Border Width Vertical', description: 'Draws a border on the top and bottom sides.', preview: 'box' },
  'border-top-style,border-top-width': { category: 'borders', title: 'Border Width Top', description: 'Draws a border on the top side only.', preview: 'box' },
  'border-right-style,border-right-width': { category: 'borders', title: 'Border Width Right', description: 'Draws a border on the right side only.', preview: 'box' },
  'border-bottom-style,border-bottom-width': { category: 'borders', title: 'Border Width Bottom', description: 'Draws a border on the bottom side only.', preview: 'box' },
  'border-left-style,border-left-width': { category: 'borders', title: 'Border Width Left', description: 'Draws a border on the left side only.', preview: 'box' },
  'border-inline-start-style,border-inline-start-width': { category: 'borders', title: 'Border Width Inline Start', description: 'Draws a border at the start of the inline axis — the left in LTR, the right in RTL.', preview: 'box' },
  'border-inline-end-style,border-inline-end-width': { category: 'borders', title: 'Border Width Inline End', description: 'Draws a border at the end of the inline axis — the right in LTR, the left in RTL.', preview: 'box' },
  'border-block-start-style,border-block-start-width': { category: 'borders', title: 'Border Width Block Start', description: 'Draws a border at the start of the block axis (the top, in horizontal writing modes).', preview: 'box' },
  'border-block-end-style,border-block-end-width': { category: 'borders', title: 'Border Width Block End', description: 'Draws a border at the end of the block axis (the bottom, in horizontal writing modes).', preview: 'box' },
  'border-color': { category: 'borders', title: 'Border Color', description: 'Colours all four borders.', preview: 'color' },
  'border-inline-color': { category: 'borders', title: 'Border Color Horizontal', description: 'Colours the left and right borders.', preview: 'color' },
  'border-block-color': { category: 'borders', title: 'Border Color Vertical', description: 'Colours the top and bottom borders.', preview: 'color' },
  'border-top-color': { category: 'borders', title: 'Border Color Top', description: 'Colours the top border only.', preview: 'color' },
  'border-right-color': { category: 'borders', title: 'Border Color Right', description: 'Colours the right border only.', preview: 'color' },
  'border-bottom-color': { category: 'borders', title: 'Border Color Bottom', description: 'Colours the bottom border only.', preview: 'color' },
  'border-left-color': { category: 'borders', title: 'Border Color Left', description: 'Colours the left border only.', preview: 'color' },
  'border-inline-start-color': { category: 'borders', title: 'Border Color Inline Start', description: 'Colours the border at the start of the inline axis.', preview: 'color' },
  'border-inline-end-color': { category: 'borders', title: 'Border Color Inline End', description: 'Colours the border at the end of the inline axis.', preview: 'color' },
  'border-block-start-color': { category: 'borders', title: 'Border Color Block Start', description: 'Colours the border at the start of the block axis.', preview: 'color' },
  'border-block-end-color': { category: 'borders', title: 'Border Color Block End', description: 'Colours the border at the end of the block axis.', preview: 'color' },
  'border-style': { category: 'borders', title: 'Border Style', description: 'Draws the border solid, dashed, dotted, doubled, or removes it.', preview: 'box' },
  'border-inline-style,border-inline-start-width,border-inline-end-width': { category: 'borders', title: 'Divide Horizontal', description: 'Draws a vertical rule between an element’s children by bordering all but the first — a separated row without touching the children.', preview: 'none' },
  'border-bottom-style,border-top-style,border-top-width,border-bottom-width': { category: 'borders', title: 'Divide Vertical', description: 'Draws a horizontal rule between an element’s stacked children by bordering all but the first.', preview: 'none' },
  '--tw-divide-x-reverse': { category: 'borders', title: 'Divide Horizontal Reverse', description: 'Flips which side the horizontal divider lands on, for a row rendered in reverse order.', preview: 'none' },
  '--tw-divide-y-reverse': { category: 'borders', title: 'Divide Vertical Reverse', description: 'Flips which side the vertical divider lands on, for a column rendered in reverse order.', preview: 'none' },
  'outline-style,outline-width': { category: 'borders', title: 'Outline Width', description: 'Draws an outline, which sits outside the border and never affects layout — the right tool for focus rings.', preview: 'box' },
  'outline-color': { category: 'borders', title: 'Outline Color', description: 'Colours the outline — the ring drawn outside the border, which never affects layout.', preview: 'color' },
  'outline-style': { category: 'borders', title: 'Outline Style', description: 'Draws the outline solid, dashed, dotted or doubled.', preview: 'box' },
  'outline-offset': { category: 'borders', title: 'Outline Offset', description: 'Pushes the outline away from the element’s edge, leaving a gap between border and ring.', preview: 'box' },
  'outline-style,outline,outline-offset': { category: 'borders', title: 'Outline Hidden', description: 'Hides the default focus outline while keeping one visible in forced-colours mode — never remove a focus indicator without providing your own.', preview: 'none' },

  // ── Effects ───────────────────────────────────────────────────────────────────────────────────
  'box-shadow': { category: 'effects', title: 'Box Shadow & Ring', description: 'Casts a drop shadow, or draws a ring — both compile to `box-shadow`, so they compose in one declaration.', preview: 'box' },
  '--tw-shadow-color': { category: 'effects', title: 'Shadow Color', description: 'Tints the box shadow, instead of the default neutral black.', preview: 'color' },
  '--tw-inset-shadow-color': { category: 'effects', title: 'Inset Shadow Color', description: 'Tints an inset box shadow.', preview: 'color' },
  '--tw-ring-color': { category: 'effects', title: 'Ring Color', description: 'Colours the ring — the offset outline drawn with `box-shadow`, most often a focus indicator.', preview: 'color' },
  '--tw-ring-inset': { category: 'effects', title: 'Ring Inset', description: 'Draws the ring inside the element’s bounds rather than around them.', preview: 'none' },
  '--tw-ring-offset-width,--tw-ring-offset-shadow': { category: 'effects', title: 'Ring Offset Width', description: 'Inserts a gap between the element and its ring, painted in the ring-offset colour.', preview: 'box' },
  '--tw-ring-offset-color': { category: 'effects', title: 'Ring Offset Color', description: 'Colours the gap between the element and its ring — usually matched to the background behind it.', preview: 'color' },
  '--tw-inset-ring-color': { category: 'effects', title: 'Inset Ring Color', description: 'Colours an inset ring.', preview: 'color' },
  'text-shadow': { category: 'effects', title: 'Text Shadow', description: 'Casts a shadow behind the text itself.', preview: 'text' },
  '--tw-text-shadow-color': { category: 'effects', title: 'Text Shadow Color', description: 'Tints the text shadow.', preview: 'color' },
  opacity: { category: 'effects', title: 'Opacity', description: 'Fades the whole element, children included.', preview: 'box' },
  'mix-blend-mode': { category: 'effects', title: 'Mix Blend Mode', description: 'Blends an element into the content painted behind it.', preview: 'none' },
  'mask-image,mask-composite': { category: 'effects', title: 'Mask Image', description: 'Fades or cuts away part of an element using a gradient as a mask — for edge fades and reveal effects.', preview: 'none' },
  'mask-image': { category: 'effects', title: 'Mask None', description: 'Removes any mask image applied further up.', preview: 'none' },
  'mask-composite': { category: 'effects', title: 'Mask Composite', description: 'Chooses how multiple mask layers combine — added, subtracted, intersected or excluded.', preview: 'none' },
  'mask-position': { category: 'effects', title: 'Mask Position', description: 'Anchors the mask image to an edge or corner of the box.', preview: 'none' },
  'mask-size': { category: 'effects', title: 'Mask Size', description: 'Scales the mask image to cover the box, fit inside it, or keep its own size.', preview: 'none' },
  'mask-repeat': { category: 'effects', title: 'Mask Repeat', description: 'Controls whether and how the mask image tiles.', preview: 'none' },
  'mask-origin': { category: 'effects', title: 'Mask Origin', description: 'Chooses which box the mask image is positioned against.', preview: 'none' },
  'mask-clip': { category: 'effects', title: 'Mask Clip', description: 'Chooses how far the mask extends across the element’s boxes.', preview: 'none' },
  'mask-mode': { category: 'effects', title: 'Mask Mode', description: 'Reads the mask from its alpha channel or its luminance.', preview: 'none' },
  'mask-type': { category: 'effects', title: 'Mask Type', description: 'Sets how an SVG mask element is interpreted — by alpha or by luminance.', preview: 'none' },
  '--tw-mask-radial-position': { category: 'effects', title: 'Radial Mask Position', description: 'Anchors the centre of a radial gradient mask.', preview: 'none' },
  '--tw-mask-radial-size': { category: 'effects', title: 'Radial Mask Size', description: 'Sizes a radial gradient mask against the nearest or farthest side or corner.', preview: 'none' },
  '--tw-mask-radial-shape': { category: 'effects', title: 'Radial Mask Shape', description: 'Draws a radial gradient mask as a circle or an ellipse.', preview: 'none' },

  // ── Filters ───────────────────────────────────────────────────────────────────────────────────
  filter: { category: 'filters', title: 'Filter', description: 'Applies a graphical filter to the element — blur, brightness, contrast, grayscale, hue rotation, saturation, sepia.', preview: 'box' },
  '-webkit-backdrop-filter,backdrop-filter': { category: 'filters', title: 'Backdrop Filter', description: 'Applies a filter to whatever is BEHIND the element — the frosted-glass effect, which needs a translucent background to show.', preview: 'box' },
  '--tw-drop-shadow-color,--tw-drop-shadow': { category: 'filters', title: 'Drop Shadow Color', description: 'Tints a drop-shadow filter, which follows an image’s alpha outline rather than its box.', preview: 'color' },

  // ── Tables ────────────────────────────────────────────────────────────────────────────────────
  'border-collapse': { category: 'tables', title: 'Border Collapse', description: 'Merges adjacent table cell borders into one, or keeps them separate.', preview: 'none' },
  'border-spacing': { category: 'tables', title: 'Border Spacing', description: 'Sets the gap between separated table cell borders.', preview: 'size' },
  'table-layout': { category: 'tables', title: 'Table Layout', description: 'Sizes table columns from their content, or fixes them from the first row for predictable, faster layout.', preview: 'none' },
  'caption-side': { category: 'tables', title: 'Caption Side', description: 'Places a table caption above or below the table.', preview: 'none' },

  // ── Transitions & Animation ───────────────────────────────────────────────────────────────────
  'transition-property,transition-timing-function,transition-duration': { category: 'transitions', title: 'Transition Property', description: 'Animates changes to a chosen set of properties, with a sensible default easing and duration built in.', preview: 'none' },
  'transition-property': { category: 'transitions', title: 'Transition None', description: 'Turns transitions off, so changes apply instantly.', preview: 'none' },
  'transition-duration': { category: 'transitions', title: 'Transition Duration', description: 'Sets how long the transition takes.', preview: 'none' },
  '--tw-duration': { category: 'transitions', title: 'Transition Duration Initial', description: 'Resets the duration to its initial value, letting an inherited or default duration take over again.', preview: 'none' },
  'transition-timing-function': { category: 'transitions', title: 'Transition Timing Function', description: 'Sets the easing curve — how the transition accelerates and settles.', preview: 'none' },
  '--tw-ease': { category: 'transitions', title: 'Transition Easing Initial', description: 'Resets the easing to its initial value.', preview: 'none' },
  'transition-delay': { category: 'transitions', title: 'Transition Delay', description: 'Waits before the transition starts — the basis of a staggered reveal.', preview: 'none' },
  'transition-behavior': { category: 'transitions', title: 'Transition Behavior', description: 'Allows discrete properties, like `display`, to participate in a transition instead of snapping.', preview: 'none' },
  animation: { category: 'transitions', title: 'Animation', description: 'Runs a built-in keyframe animation — spin, ping, pulse or bounce.', preview: 'box' },

  // ── Transforms ────────────────────────────────────────────────────────────────────────────────
  transform: { category: 'transforms', title: 'Transform', description: 'The composed transform — rotation on the X and Y axes, skew, and the 3D machinery.', preview: 'none' },
  translate: { category: 'transforms', title: 'Translate', description: 'Moves an element from where layout put it, without disturbing anything around it.', preview: 'none' },
  rotate: { category: 'transforms', title: 'Rotate', description: 'Rotates an element around its transform origin.', preview: 'none' },
  scale: { category: 'transforms', title: 'Scale', description: 'Grows or shrinks an element about its transform origin — the usual hover-lift ingredient.', preview: 'none' },
  zoom: { category: 'transforms', title: 'Zoom', description: 'Scales an element AND the space it occupies, unlike `scale`, which leaves the layout box untouched.', preview: 'none' },
  'transform-origin': { category: 'transforms', title: 'Transform Origin', description: 'Moves the pivot that rotation and scaling act around.', preview: 'none' },
  'transform-style': { category: 'transforms', title: 'Transform Style', description: 'Decides whether children are flattened into the parent’s plane or keep their own position in 3D.', preview: 'none' },
  'transform-box': { category: 'transforms', title: 'Transform Box', description: 'Chooses the reference box a transform is measured against — matters most for transformed SVG elements.', preview: 'none' },
  'backface-visibility': { category: 'transforms', title: 'Backface Visibility', description: 'Shows or hides an element’s reverse side once it has been rotated past 90°.', preview: 'none' },
  perspective: { category: 'transforms', title: 'Perspective', description: 'Sets how far the viewer is from the z=0 plane — smaller values exaggerate the 3D effect.', preview: 'none' },
  'perspective-origin': { category: 'transforms', title: 'Perspective Origin', description: 'Moves the vanishing point that perspective is projected toward.', preview: 'none' },

  // ── Interactivity ─────────────────────────────────────────────────────────────────────────────
  'accent-color': { category: 'interactivity', title: 'Accent Color', description: 'Tints a native form control — checkbox, radio, range — without rebuilding it.', preview: 'color' },
  appearance: { category: 'interactivity', title: 'Appearance', description: 'Strips a native control’s platform styling so it can be styled from scratch.', preview: 'none' },
  'caret-color': { category: 'interactivity', title: 'Caret Color', description: 'Colours the text insertion cursor in an input or textarea.', preview: 'color' },
  'color-scheme': { category: 'interactivity', title: 'Color Scheme', description: 'Tells the browser which scheme this subtree is drawn for, so native controls and scrollbars match.', preview: 'none' },
  cursor: { category: 'interactivity', title: 'Cursor', description: 'Sets the mouse cursor shown over the element.', preview: 'cursor' },
  'field-sizing': { category: 'interactivity', title: 'Field Sizing', description: 'Lets a text field grow with its content instead of staying at a fixed size.', preview: 'none' },
  'pointer-events': { category: 'interactivity', title: 'Pointer Events', description: 'Makes an element transparent to clicks, so they land on whatever is behind it.', preview: 'none' },
  resize: { category: 'interactivity', title: 'Resize', description: 'Controls which axes the user can drag to resize an element.', preview: 'none' },
  'scroll-behavior': { category: 'interactivity', title: 'Scroll Behavior', description: 'Makes programmatic scrolling and in-page anchor jumps animate smoothly.', preview: 'none' },
  'scroll-margin': { category: 'interactivity', title: 'Scroll Margin', description: 'Adds breathing room around an element when it is scrolled into view — how you stop a sticky header covering an anchor target.', preview: 'size' },
  'scroll-margin-inline': { category: 'interactivity', title: 'Scroll Margin Horizontal', description: 'Adds left and right breathing room when an element is scrolled into view.', preview: 'size' },
  'scroll-margin-block': { category: 'interactivity', title: 'Scroll Margin Vertical', description: 'Adds top and bottom breathing room when an element is scrolled into view.', preview: 'size' },
  'scroll-margin-top': { category: 'interactivity', title: 'Scroll Margin Top', description: 'Adds breathing room above an element when it is scrolled into view.', preview: 'size' },
  'scroll-margin-right': { category: 'interactivity', title: 'Scroll Margin Right', description: 'Adds breathing room to the right of an element when it is scrolled into view.', preview: 'size' },
  'scroll-margin-bottom': { category: 'interactivity', title: 'Scroll Margin Bottom', description: 'Adds breathing room below an element when it is scrolled into view.', preview: 'size' },
  'scroll-margin-left': { category: 'interactivity', title: 'Scroll Margin Left', description: 'Adds breathing room to the left of an element when it is scrolled into view.', preview: 'size' },
  'scroll-margin-inline-start': { category: 'interactivity', title: 'Scroll Margin Inline Start', description: 'Adds scroll breathing room at the start of the inline axis.', preview: 'size' },
  'scroll-margin-inline-end': { category: 'interactivity', title: 'Scroll Margin Inline End', description: 'Adds scroll breathing room at the end of the inline axis.', preview: 'size' },
  'scroll-margin-block-start': { category: 'interactivity', title: 'Scroll Margin Block Start', description: 'Adds scroll breathing room at the start of the block axis.', preview: 'size' },
  'scroll-margin-block-end': { category: 'interactivity', title: 'Scroll Margin Block End', description: 'Adds scroll breathing room at the end of the block axis.', preview: 'size' },
  'scroll-padding': { category: 'interactivity', title: 'Scroll Padding', description: 'Insets the scrollport, so snapped or scrolled-to children stop short of the container’s edges.', preview: 'size' },
  'scroll-padding-inline': { category: 'interactivity', title: 'Scroll Padding Horizontal', description: 'Insets the scrollport on its left and right edges.', preview: 'size' },
  'scroll-padding-block': { category: 'interactivity', title: 'Scroll Padding Vertical', description: 'Insets the scrollport on its top and bottom edges.', preview: 'size' },
  'scroll-padding-top': { category: 'interactivity', title: 'Scroll Padding Top', description: 'Insets the top edge of the scrollport.', preview: 'size' },
  'scroll-padding-right': { category: 'interactivity', title: 'Scroll Padding Right', description: 'Insets the right edge of the scrollport.', preview: 'size' },
  'scroll-padding-bottom': { category: 'interactivity', title: 'Scroll Padding Bottom', description: 'Insets the bottom edge of the scrollport.', preview: 'size' },
  'scroll-padding-left': { category: 'interactivity', title: 'Scroll Padding Left', description: 'Insets the left edge of the scrollport.', preview: 'size' },
  'scroll-padding-inline-start': { category: 'interactivity', title: 'Scroll Padding Inline Start', description: 'Insets the scrollport at the start of the inline axis.', preview: 'size' },
  'scroll-padding-inline-end': { category: 'interactivity', title: 'Scroll Padding Inline End', description: 'Insets the scrollport at the end of the inline axis.', preview: 'size' },
  'scroll-padding-block-start': { category: 'interactivity', title: 'Scroll Padding Block Start', description: 'Insets the scrollport at the start of the block axis.', preview: 'size' },
  'scroll-padding-block-end': { category: 'interactivity', title: 'Scroll Padding Block End', description: 'Insets the scrollport at the end of the block axis.', preview: 'size' },
  'scroll-snap-type': { category: 'interactivity', title: 'Scroll Snap Type', description: 'Turns a scroll container into a snapping one, on either or both axes.', preview: 'none' },
  'scroll-snap-align': { category: 'interactivity', title: 'Scroll Snap Align', description: 'Chooses which edge of a child aligns to the snap position.', preview: 'none' },
  'scroll-snap-stop': { category: 'interactivity', title: 'Scroll Snap Stop', description: 'Forbids a fast scroll from skipping past a snap point.', preview: 'none' },
  '--tw-scroll-snap-strictness': { category: 'interactivity', title: 'Scroll Snap Strictness', description: 'Chooses whether snapping is mandatory or merely a suggestion the browser may ignore.', preview: 'none' },
  'scrollbar-width': { category: 'interactivity', title: 'Scrollbar Width', description: 'Renders a thinner scrollbar, or hides it while keeping the element scrollable.', preview: 'none' },
  'scrollbar-color': { category: 'interactivity', title: 'Scrollbar Color', description: 'Colours the scrollbar thumb and track.', preview: 'color' },
  'scrollbar-gutter': { category: 'interactivity', title: 'Scrollbar Gutter', description: 'Reserves space for the scrollbar even when it is not showing, so content does not shift when it appears.', preview: 'none' },
  'touch-action': { category: 'interactivity', title: 'Touch Action', description: 'Decides which touch gestures the browser handles itself rather than passing to your handlers.', preview: 'none' },
  '-webkit-user-select,user-select': { category: 'interactivity', title: 'User Select', description: 'Controls what the user can select with a drag — `select-none` for UI chrome that should not highlight.', preview: 'none' },
  'will-change': { category: 'interactivity', title: 'Will Change', description: 'Warns the browser that a property is about to animate. Use sparingly — it costs memory and can hurt if left on.', preview: 'none' },

  // ── SVG ───────────────────────────────────────────────────────────────────────────────────────
  fill: { category: 'svg', title: 'Fill Color', description: 'Fills an SVG shape. `fill-current` inherits the text colour, which is how icons follow their surroundings.', preview: 'color' },
  stroke: { category: 'svg', title: 'Stroke Color', description: 'Colours an SVG shape’s outline.', preview: 'color' },
  'stroke-width': { category: 'svg', title: 'Stroke Width', description: 'Sets the thickness of an SVG shape’s outline.', preview: 'none' },

  // ── Accessibility ─────────────────────────────────────────────────────────────────────────────
  'position,width,height,padding,margin,overflow,clip-path,white-space,border-width': { category: 'accessibility', title: 'Screen-Reader Only', description: 'Hides content visually while keeping it in the accessibility tree — for labels a sighted user gets from context.', preview: 'none' },
  'position,width,height,padding,margin,overflow,clip-path,white-space': { category: 'accessibility', title: 'Not Screen-Reader Only', description: 'Reveals screen-reader-only content again, typically on focus so a skip link appears when tabbed to.', preview: 'none' },
  'forced-color-adjust': { category: 'accessibility', title: 'Forced Color Adjust', description: 'Opts an element out of forced-colours mode, for cases where the user’s palette would destroy meaning — a colour swatch, say.', preview: 'none' },
};
