// CHROME UI STRINGS — the site-wide skeleton slots (top nav, mobile nav, footer, cookie banner)
// are SHARED across every locale (one markup, rendered per page), so their labels cannot live in
// per-page `page.data`. They localize through `website.data.strings` instead, read with the
// double-lookup pattern (the flag switcher's existing trick, generated by `S()` in website.ts):
//
//   {{lookup (lookup @root.website.data.strings @root.page.locale) 'nav_cta'}}
//
// `page.locale` is bound on every page/slot render (publish AND preview), so each locale's pages
// pick their own string set from ONE shared chrome source. `href_*` keys are link TARGETS (the
// publish link-rebase does NOT locale-prefix hrefs, so each locale points at its own routes).
// Every locale in EXAMPLE_LOCALES must carry the SAME key set (guarded by seed-content tests).

export interface ChromeStrings {
  /** The brand/logo link target — each locale's own home ('/' vs '/de'). */
  href_home: string;
  /** Top-nav CTA label + target. */
  nav_cta: string;
  href_contact: string;
  /** Mobile nav: the hamburger dropdown summary label. */
  mobile_menu: string;
  /** The language switcher's accessible group label. */
  aria_language: string;
  /** Footer column headings. */
  footer_studio: string;
  footer_contact: string;
  footer_legal: string;
  footer_news_title: string;
  /** Footer newsletter blurb + CTA. */
  footer_news: string;
  footer_btn: string;
  /** Footer bottom line (after the © legal name). */
  footer_built: string;
  /** Cookie-consent banner (bottom slot). */
  cookie_text: string;
  cookie_more: string;
  cookie_accept: string;
  href_privacy: string;
}

export const CHROME_STRINGS: Record<string, ChromeStrings> = {
  en: {
    href_home: '/',
    nav_cta: 'Start a project',
    href_contact: '/contact',
    mobile_menu: 'Menu',
    aria_language: 'Language',
    footer_studio: 'Studio',
    footer_contact: 'Contact',
    footer_legal: 'Legal',
    footer_news_title: 'Newsletter',
    footer_news: 'Occasional notes on web craft. No spam.',
    footer_btn: 'Get in touch',
    footer_built: 'Built with Sitewright — code-first, instantly fast.',
    cookie_text: 'We use a few essential cookies to make this site work and anonymous analytics to improve it.',
    cookie_more: 'Learn more',
    cookie_accept: 'OK, got it',
    href_privacy: '/privacy',
  },
  de: {
    href_home: '/de',
    nav_cta: 'Projekt starten',
    href_contact: '/de/kontakt',
    mobile_menu: 'Menü',
    aria_language: 'Sprache',
    footer_studio: 'Studio',
    footer_contact: 'Kontakt',
    footer_legal: 'Rechtliches',
    footer_news_title: 'Newsletter',
    footer_news: 'Gelegentliche Notizen zum Webhandwerk. Kein Spam.',
    footer_btn: 'Kontakt aufnehmen',
    footer_built: 'Gebaut mit Sitewright — code-first und sofort schnell.',
    cookie_text: 'Wir verwenden wenige notwendige Cookies für den Betrieb dieser Website und anonyme Statistiken zu ihrer Verbesserung.',
    cookie_more: 'Mehr erfahren',
    cookie_accept: 'Alles klar',
    href_privacy: '/de/datenschutz',
  },
  es: {
    href_home: '/es',
    nav_cta: 'Empezar un proyecto',
    href_contact: '/es/contacto',
    mobile_menu: 'Menú',
    aria_language: 'Idioma',
    footer_studio: 'Estudio',
    footer_contact: 'Contacto',
    footer_legal: 'Legal',
    footer_news_title: 'Boletín',
    footer_news: 'Notas ocasionales sobre el oficio web. Nada de spam.',
    footer_btn: 'Escríbanos',
    footer_built: 'Hecho con Sitewright — code-first y rápido desde el primer momento.',
    cookie_text: 'Usamos unas pocas cookies esenciales para que esta web funcione y estadística anónima para mejorarla.',
    cookie_more: 'Más información',
    cookie_accept: 'Entendido',
    href_privacy: '/es/privacidad',
  },
};
