// CHROME UI STRINGS — the site-wide skeleton slots (top nav, mobile nav, footer, cookie banner)
// are SHARED across every locale (one markup, rendered per page), so their labels cannot live in
// per-page `page.data`. They localize through the dedicated translation catalog (`website.translations`)
// instead, read with the `{{sw-translate "key"}}` helper (generated by `S()`/`SL()` in website.ts):
//
//   {{sw-translate "nav_cta"}}        (and `(sw-translate "href_home")` as a subexpression)
//
// `page.locale` is bound on every page/slot render (publish AND preview), and the render projection
// pre-resolves the catalog per page-locale into `website.t`, so each locale's pages pick their own
// string set from ONE shared chrome source. `href_*` keys are link TARGETS (the publish link-rebase
// does NOT locale-prefix hrefs, so each locale points at its own routes). CHROME_STRINGS below is the
// authored locale-first source (readable + parity-checked); `CHROME_TRANSLATIONS` is its derived
// key-first projection (what `website.translations` is seeded with). Every locale in EXAMPLE_LOCALES
// must carry the SAME key set (guarded by seed-content tests).

export interface ChromeStrings {
  /** The brand/logo link target — each locale's own home ('/' vs '/de'). */
  href_home: string;
  /** Top-nav CTA label + target. */
  nav_cta: string;
  href_contact: string;
  /** Mobile nav: the hamburger dropdown summary label. */
  mobile_menu: string;
  /** The language switcher's accessible group label. */
  aria_language: string;
  /** Footer column headings. */
  footer_studio: string;
  footer_contact: string;
  footer_legal: string;
  footer_news_title: string;
  /** Footer newsletter blurb + CTA. */
  footer_news: string;
  footer_btn: string;
  /** Footer bottom line (after the © legal name). */
  footer_built: string;
  /** Cookie-consent banner (bottom slot). */
  cookie_text: string;
  cookie_more: string;
  cookie_accept: string;
  href_privacy: string;
  // MINI SHOP cart — RESERVED keys the {{sw-add-to-cart}}/{{sw-cart}} helpers read from the catalog so a
  // bare helper auto-localizes its built-in labels (no per-page hash). See packages/blocks reservedTr.
  cart_add: string;
  cart_title: string;
  cart_toggle: string;
  cart_note: string;
  cart_added: string;
  cart_empty: string;
  cart_total: string;
  cart_clear: string;
  cart_sent: string;
  cart_order_lead: string;
  cart_currency_symbol: string;
  cart_currency_code: string;
  // COLOR SCHEMES (RESERVED) — accessible label for the {{sw-theme-toggle}} light/dark button.
  theme_toggle: string;
  // CONSENT MANAGER (RESERVED) — the {{sw-consent}} banner + per-category preferences copy.
  consent_title: string;
  consent_intro: string;
  consent_accept_all: string;
  consent_reject_all: string;
  consent_customize: string;
  consent_save: string;
  consent_prefs_title: string;
  consent_settings: string;
  consent_privacy: string;
  consent_necessary: string;
  consent_necessary_desc: string;
  consent_functional: string;
  consent_functional_desc: string;
  consent_analytics: string;
  consent_analytics_desc: string;
  consent_marketing: string;
  consent_marketing_desc: string;
  consent_allow_once: string;
  consent_always_allow: string;
  consent_embed_note: string;
  // SYSTEM component UI strings (RESERVED) — the first-party component runtimes read these via the
  // injected window.__SW_T__ (modal close button + carousel a11y). {n}/{total} are runtime-filled.
  close: string;
  slide_prev: string;
  slide_next: string;
  slide_x_of_y: string;
  go_to_slide: string;
  carousel_label: string;
}

export const CHROME_STRINGS: Record<string, ChromeStrings> = {
  en: {
    href_home: '/',
    nav_cta: 'Start a project',
    href_contact: '/contact',
    mobile_menu: 'Menu',
    aria_language: 'Language',
    footer_studio: 'Studio',
    footer_contact: 'Contact',
    footer_legal: 'Legal',
    footer_news_title: 'Newsletter',
    footer_news: 'Occasional notes on web craft. No spam.',
    footer_btn: 'Get in touch',
    footer_built: 'Built with Sitewright — code-first, instantly fast.',
    cookie_text: 'We use a few essential cookies to make this site work and anonymous analytics to improve it.',
    cookie_more: 'Learn more',
    cookie_accept: 'OK, got it',
    href_privacy: '/privacy',
    cart_add: 'Add to cart',
    cart_title: 'Your cart',
    cart_toggle: 'Shopping Cart',
    cart_note: 'Prices are indicative. This sends an order request — the seller confirms availability and final price.',
    cart_added: 'Added',
    cart_empty: 'Your cart is empty.',
    cart_total: 'Total',
    cart_clear: 'Clear cart',
    cart_sent: 'Order sent — we will be in touch.',
    cart_order_lead: 'I’d like to order:',
    cart_currency_symbol: '$',
    cart_currency_code: 'USD',
    theme_toggle: 'Toggle dark mode',
    consent_title: 'We value your privacy',
    consent_intro: 'We use cookies to enhance your experience and analyze our traffic. Choose which categories you allow.',
    consent_accept_all: 'Accept all',
    consent_reject_all: 'Reject all',
    consent_customize: 'Customize',
    consent_save: 'Save preferences',
    consent_prefs_title: 'Privacy preferences',
    consent_settings: 'Cookie settings',
    consent_privacy: 'Privacy policy',
    consent_necessary: 'Strictly necessary',
    consent_necessary_desc: 'Required for the site to function. Always on.',
    consent_functional: 'Functional',
    consent_functional_desc: 'Remembers your preferences and enables enhanced features.',
    consent_analytics: 'Analytics',
    consent_analytics_desc: 'Helps us understand how visitors use the site.',
    consent_marketing: 'Marketing',
    consent_marketing_desc: 'Used to deliver relevant ads and measure campaigns.',
    consent_allow_once: 'Allow once',
    consent_always_allow: 'Always allow',
    consent_embed_note: 'This content is loaded from a third party. Allow it to load?',
    close: 'Close',
    slide_prev: 'Previous slide',
    slide_next: 'Next slide',
    slide_x_of_y: 'Slide {n} of {total}',
    go_to_slide: 'Go to slide {n}',
    carousel_label: 'carousel',
  },
  de: {
    href_home: '/de',
    nav_cta: 'Projekt starten',
    href_contact: '/de/kontakt',
    mobile_menu: 'Menü',
    aria_language: 'Sprache',
    footer_studio: 'Studio',
    footer_contact: 'Kontakt',
    footer_legal: 'Rechtliches',
    footer_news_title: 'Newsletter',
    footer_news: 'Gelegentliche Notizen zum Webhandwerk. Kein Spam.',
    footer_btn: 'Kontakt aufnehmen',
    footer_built: 'Gebaut mit Sitewright — code-first und sofort schnell.',
    cookie_text: 'Wir verwenden wenige notwendige Cookies für den Betrieb dieser Website und anonyme Statistiken zu ihrer Verbesserung.',
    cookie_more: 'Mehr erfahren',
    cookie_accept: 'Alles klar',
    href_privacy: '/de/datenschutz',
    cart_add: 'In den Warenkorb',
    cart_title: 'Warenkorb',
    cart_toggle: 'Warenkorb',
    cart_note: 'Preise unverbindlich. Dies sendet eine Bestellanfrage — der Verkäufer bestätigt Verfügbarkeit und Endpreis.',
    cart_added: 'Hinzugefügt',
    cart_empty: 'Ihr Warenkorb ist leer.',
    cart_total: 'Gesamt',
    cart_clear: 'Warenkorb leeren',
    cart_sent: 'Bestellung gesendet — wir melden uns.',
    cart_order_lead: 'Ich möchte gerne bestellen:',
    cart_currency_symbol: '$',
    cart_currency_code: 'USD',
    theme_toggle: 'Dunkelmodus umschalten',
    consent_title: 'Wir schätzen Ihre Privatsphäre',
    consent_intro: 'Wir verwenden Cookies, um Ihr Erlebnis zu verbessern und unseren Verkehr zu analysieren. Wählen Sie, welche Kategorien Sie zulassen.',
    consent_accept_all: 'Alle akzeptieren',
    consent_reject_all: 'Alle ablehnen',
    consent_customize: 'Anpassen',
    consent_save: 'Einstellungen speichern',
    consent_prefs_title: 'Datenschutzeinstellungen',
    consent_settings: 'Cookie-Einstellungen',
    consent_privacy: 'Datenschutzerklärung',
    consent_necessary: 'Unbedingt erforderlich',
    consent_necessary_desc: 'Für den Betrieb der Website erforderlich. Immer aktiv.',
    consent_functional: 'Funktional',
    consent_functional_desc: 'Speichert Ihre Einstellungen und ermöglicht erweiterte Funktionen.',
    consent_analytics: 'Statistik',
    consent_analytics_desc: 'Hilft uns zu verstehen, wie Besucher die Website nutzen.',
    consent_marketing: 'Marketing',
    consent_marketing_desc: 'Dient dazu, relevante Werbung auszuspielen und Kampagnen zu messen.',
    consent_allow_once: 'Einmal erlauben',
    consent_always_allow: 'Immer erlauben',
    consent_embed_note: 'Dieser Inhalt wird von einem Drittanbieter geladen. Laden zulassen?',
    close: 'Schließen',
    slide_prev: 'Vorherige Folie',
    slide_next: 'Nächste Folie',
    slide_x_of_y: 'Folie {n} von {total}',
    go_to_slide: 'Zu Folie {n}',
    carousel_label: 'Karussell',
  },
  es: {
    href_home: '/es',
    nav_cta: 'Empezar un proyecto',
    href_contact: '/es/contacto',
    mobile_menu: 'Menú',
    aria_language: 'Idioma',
    footer_studio: 'Estudio',
    footer_contact: 'Contacto',
    footer_legal: 'Legal',
    footer_news_title: 'Boletín',
    footer_news: 'Notas ocasionales sobre el oficio web. Nada de spam.',
    footer_btn: 'Escríbanos',
    footer_built: 'Hecho con Sitewright — code-first y rápido desde el primer momento.',
    cookie_text: 'Usamos unas pocas cookies esenciales para que esta web funcione y estadística anónima para mejorarla.',
    cookie_more: 'Más información',
    cookie_accept: 'Entendido',
    href_privacy: '/es/privacidad',
    cart_add: 'Añadir al carrito',
    cart_title: 'Su carrito',
    cart_toggle: 'Carrito',
    cart_note: 'Precios orientativos. Esto envía una solicitud de pedido — el vendedor confirma disponibilidad y precio final.',
    cart_added: 'Añadido',
    cart_empty: 'Su carrito está vacío.',
    cart_total: 'Total',
    cart_clear: 'Vaciar carrito',
    cart_sent: 'Pedido enviado — le contactaremos.',
    cart_order_lead: 'Me gustaría hacer un pedido:',
    cart_currency_symbol: '$',
    cart_currency_code: 'USD',
    theme_toggle: 'Cambiar modo oscuro',
    consent_title: 'Valoramos su privacidad',
    consent_intro: 'Usamos cookies para mejorar su experiencia y analizar nuestro tráfico. Elija qué categorías permite.',
    consent_accept_all: 'Aceptar todo',
    consent_reject_all: 'Rechazar todo',
    consent_customize: 'Personalizar',
    consent_save: 'Guardar preferencias',
    consent_prefs_title: 'Preferencias de privacidad',
    consent_settings: 'Configuración de cookies',
    consent_privacy: 'Política de privacidad',
    consent_necessary: 'Estrictamente necesarias',
    consent_necessary_desc: 'Necesarias para que el sitio funcione. Siempre activas.',
    consent_functional: 'Funcionales',
    consent_functional_desc: 'Recuerda sus preferencias y habilita funciones mejoradas.',
    consent_analytics: 'Analíticas',
    consent_analytics_desc: 'Nos ayuda a entender cómo usan el sitio los visitantes.',
    consent_marketing: 'Marketing',
    consent_marketing_desc: 'Se usa para mostrar anuncios relevantes y medir campañas.',
    consent_allow_once: 'Permitir una vez',
    consent_always_allow: 'Permitir siempre',
    consent_embed_note: 'Este contenido se carga desde un tercero. ¿Permitir que se cargue?',
    close: 'Cerrar',
    slide_prev: 'Diapositiva anterior',
    slide_next: 'Diapositiva siguiente',
    slide_x_of_y: 'Diapositiva {n} de {total}',
    go_to_slide: 'Ir a la diapositiva {n}',
    carousel_label: 'carrusel',
  },
};

/**
 * The chrome strings transposed into the KEY-FIRST translation catalog shape used by
 * `website.translations` (`{ key: { locale: value } }`). The slots read these via `{{sw-translate "key"}}`
 * (see website.ts S()/SL()), resolved per page-locale by the render projection. CHROME_STRINGS above is
 * the authored, locale-first source (more readable + parity-checked); this is its derived projection.
 */
export const CHROME_TRANSLATIONS: Record<string, Record<string, string>> = (() => {
  const out: Record<string, Record<string, string>> = {};
  for (const [locale, strings] of Object.entries(CHROME_STRINGS)) {
    for (const [key, value] of Object.entries(strings)) {
      // eslint-disable-next-line security/detect-object-injection -- key/locale are from a typed const map
      (out[key] ??= {})[locale] = value;
    }
  }
  return out;
})();
