// CHROME UI STRINGS — the site-wide skeleton slots (top nav, mobile nav, footer, cookie banner)
// are SHARED across every locale (one markup, rendered per page), so their labels cannot live in
// per-page `page.data`. They localize through the dedicated translation catalog (`website.translations`)
// instead, read with the `{{sw-translate "key"}}` helper (generated by `S()`/`SL()` in website.ts):
//
//   {{sw-translate "nav_cta"}}        (and `(sw-translate "href_home")` as a subexpression)
//
// `page.locale` is bound on every page/slot render (publish AND preview), and the render projection
// pre-resolves the catalog per page-locale into `website.t`, so each locale's pages pick their own
// string set from ONE shared chrome source. `href_*` keys are link TARGETS (the publish link-rebase
// does NOT locale-prefix hrefs, so each locale points at its own routes). CHROME_STRINGS below is the
// authored locale-first source (readable + parity-checked); `CHROME_TRANSLATIONS` is its derived
// key-first projection (what `website.translations` is seeded with). Every locale in EXAMPLE_LOCALES
// must carry the SAME key set (guarded by seed-content tests).

export interface ChromeStrings {
  /** The brand/logo link target — each locale's own home ('/' vs '/de'). */
  href_home: string;
  /** Top-nav CTA label + target. */
  nav_cta: string;
  href_contact: string;
  /** Mobile nav: the hamburger dropdown summary label. */
  mobile_menu: string;
  /** The language switcher's accessible group label. */
  aria_language: string;
  /** Footer column headings. */
  footer_studio: string;
  footer_contact: string;
  footer_legal: string;
  footer_news_title: string;
  /** Footer newsletter blurb + CTA. */
  footer_news: string;
  footer_btn: string;
  /** Footer bottom line (after the © legal name). */
  footer_built: string;
  /** Cookie-consent banner (bottom slot). */
  cookie_text: string;
  cookie_more: string;
  cookie_accept: string;
  href_privacy: string;
  // MINI SHOP cart — RESERVED keys the {{sw-add-to-cart}}/{{sw-cart}} helpers read from the catalog so a
  // bare helper auto-localizes its built-in labels (no per-page hash). See packages/blocks reservedTr.
  cart_add: string;
  cart_title: string;
  cart_note: string;
  cart_added: string;
  cart_empty: string;
  cart_subtotal: string;
  cart_clear: string;
  cart_sent: string;
}

export const CHROME_STRINGS: Record<string, ChromeStrings> = {
  en: {
    href_home: '/',
    nav_cta: 'Start a project',
    href_contact: '/contact',
    mobile_menu: 'Menu',
    aria_language: 'Language',
    footer_studio: 'Studio',
    footer_contact: 'Contact',
    footer_legal: 'Legal',
    footer_news_title: 'Newsletter',
    footer_news: 'Occasional notes on web craft. No spam.',
    footer_btn: 'Get in touch',
    footer_built: 'Built with Sitewright — code-first, instantly fast.',
    cookie_text: 'We use a few essential cookies to make this site work and anonymous analytics to improve it.',
    cookie_more: 'Learn more',
    cookie_accept: 'OK, got it',
    href_privacy: '/privacy',
    cart_add: 'Add to cart',
    cart_title: 'Your cart',
    cart_note: 'Prices are indicative. This sends an order request — the seller confirms availability and final price.',
    cart_added: 'Added',
    cart_empty: 'Your cart is empty.',
    cart_subtotal: 'Subtotal',
    cart_clear: 'Clear cart',
    cart_sent: 'Order sent — we will be in touch.',
  },
  de: {
    href_home: '/de',
    nav_cta: 'Projekt starten',
    href_contact: '/de/kontakt',
    mobile_menu: 'Menü',
    aria_language: 'Sprache',
    footer_studio: 'Studio',
    footer_contact: 'Kontakt',
    footer_legal: 'Rechtliches',
    footer_news_title: 'Newsletter',
    footer_news: 'Gelegentliche Notizen zum Webhandwerk. Kein Spam.',
    footer_btn: 'Kontakt aufnehmen',
    footer_built: 'Gebaut mit Sitewright — code-first und sofort schnell.',
    cookie_text: 'Wir verwenden wenige notwendige Cookies für den Betrieb dieser Website und anonyme Statistiken zu ihrer Verbesserung.',
    cookie_more: 'Mehr erfahren',
    cookie_accept: 'Alles klar',
    href_privacy: '/de/datenschutz',
    cart_add: 'In den Warenkorb',
    cart_title: 'Warenkorb',
    cart_note: 'Preise unverbindlich. Dies sendet eine Bestellanfrage — der Verkäufer bestätigt Verfügbarkeit und Endpreis.',
    cart_added: 'Hinzugefügt',
    cart_empty: 'Ihr Warenkorb ist leer.',
    cart_subtotal: 'Zwischensumme',
    cart_clear: 'Warenkorb leeren',
    cart_sent: 'Bestellung gesendet — wir melden uns.',
  },
  es: {
    href_home: '/es',
    nav_cta: 'Empezar un proyecto',
    href_contact: '/es/contacto',
    mobile_menu: 'Menú',
    aria_language: 'Idioma',
    footer_studio: 'Estudio',
    footer_contact: 'Contacto',
    footer_legal: 'Legal',
    footer_news_title: 'Boletín',
    footer_news: 'Notas ocasionales sobre el oficio web. Nada de spam.',
    footer_btn: 'Escríbanos',
    footer_built: 'Hecho con Sitewright — code-first y rápido desde el primer momento.',
    cookie_text: 'Usamos unas pocas cookies esenciales para que esta web funcione y estadística anónima para mejorarla.',
    cookie_more: 'Más información',
    cookie_accept: 'Entendido',
    href_privacy: '/es/privacidad',
    cart_add: 'Añadir al carrito',
    cart_title: 'Su carrito',
    cart_note: 'Precios orientativos. Esto envía una solicitud de pedido — el vendedor confirma disponibilidad y precio final.',
    cart_added: 'Añadido',
    cart_empty: 'Su carrito está vacío.',
    cart_subtotal: 'Subtotal',
    cart_clear: 'Vaciar carrito',
    cart_sent: 'Pedido enviado — le contactaremos.',
  },
};

/**
 * The chrome strings transposed into the KEY-FIRST translation catalog shape used by
 * `website.translations` (`{ key: { locale: value } }`). The slots read these via `{{sw-translate "key"}}`
 * (see website.ts S()/SL()), resolved per page-locale by the render projection. CHROME_STRINGS above is
 * the authored, locale-first source (more readable + parity-checked); this is its derived projection.
 */
export const CHROME_TRANSLATIONS: Record<string, Record<string, string>> = (() => {
  const out: Record<string, Record<string, string>> = {};
  for (const [locale, strings] of Object.entries(CHROME_STRINGS)) {
    for (const [key, value] of Object.entries(strings)) {
      // eslint-disable-next-line security/detect-object-injection -- key/locale are from a typed const map
      (out[key] ??= {})[locale] = value;
    }
  }
  return out;
})();
