import { test, expect } from '@playwright/test';
import { signUp } from './helpers.js';

/**
 * A multi-file drop must survive a refusal.
 *
 * ★ The loop this replaces had no per-file catch: the first throw ended the batch and every remaining
 * file was NEVER ATTEMPTED. Measured against a real instance before the fix, dropping 60 files stored
 * 30, aborted at #31 with HTTP 429, and left one banner reading "rate limit exceeded — slow down" — no
 * count, no names, and a library holding half the photos with nothing to say which half.
 *
 * The refusals are INJECTED rather than provoked. Reaching the real 500/min cap needs 500 uploads and
 * then a 60-second pause; forcing the exact response the server would send proves the same client
 * behaviour in seconds, and pins the retry path deterministically instead of by exhaustion.
 */

/**
 * A real 16x16 PNG.
 *
 * ★ Generated by sharp, not hand-assembled. A hand-made one parsed its own METADATA fine and then failed
 * the server's full decode with `vipspng: libpng read error` — every upload 500ing, which reads as "the
 * upload path is broken" rather than "the fixture is".
 */
const PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAGUlEQVQokWOI6jlBEmIY1dAzGkpRwzVpAAArnq4QfMEQAwAAAABJRU5ErkJggg==',
  'base64',
);

const files = (n: number) =>
  Array.from({ length: n }, (_, i) => ({ name: `drop-${String(i).padStart(2, '0')}.png`, mimeType: 'image/png', buffer: PNG }));

/** Playwright's glob treats `?` as a single-character wildcard, so match the upload by URL instead. */
const isUpload = (url: URL): boolean => url.pathname.endsWith('/media');

async function openFileManager(page: import('@playwright/test').Page, baseURL: string, tag: string) {
  const stamp = Date.now().toString(36) + Math.floor(Math.random() * 1e4).toString(36);
  await signUp(page, `${tag}-${stamp}@e2e.test`);
  const created = await page.request.post('/projects', { data: { name: `Drop ${stamp}`, slug: `${tag}${stamp}` } });
  expect(created.status()).toBe(201);
  await page.goto(baseURL);
  await page.getByText(`Drop ${stamp}`, { exact: true }).first().click();
  await page.getByRole('button', { name: /File Manager/i }).first().click();
  await expect(page.getByLabel('Upload files')).toBeVisible({ timeout: 60_000 });
}

test('a plain multi-file drop lands in full', async ({ page, baseURL }) => {
  // The control for the two injection tests below: without it, a broken upload path would let them
  // "pass" by failing for the wrong reason.
  test.setTimeout(180_000);
  await openFileManager(page, baseURL!, 'dropok');
  await page.getByLabel('Upload files').setInputFiles(files(5));
  for (const name of ['drop-00.png', 'drop-01.png', 'drop-02.png', 'drop-03.png', 'drop-04.png']) {
    await expect(page.getByText(name), `${name} must be in the library`).toBeVisible({ timeout: 60_000 });
  }
});

test('★ a rate-limited file is waited out and the drop still completes', async ({ page, baseURL }) => {
  test.setTimeout(180_000);
  await openFileManager(page, baseURL!, 'dropret');

  // Refuse the third upload exactly once, the way the limiter does — including the retry-after the
  // client is supposed to honour.
  let seen = 0;
  let refused = false;
  await page.route(isUpload, async (route) => {
    if (route.request().method() !== 'POST') return route.fallback();
    seen += 1;
    if (seen === 3 && !refused) {
      refused = true;
      return route.fulfill({
        status: 429,
        headers: { 'retry-after': '1', 'content-type': 'application/json' },
        body: JSON.stringify({ error: 'rate limit exceeded — slow down' }),
      });
    }
    return route.fallback();
  });

  await page.getByLabel('Upload files').setInputFiles(files(5));

  for (const name of ['drop-00.png', 'drop-01.png', 'drop-02.png', 'drop-03.png', 'drop-04.png']) {
    await expect(page.getByText(name), `${name} must be in the library`).toBeVisible({ timeout: 60_000 });
  }
  expect(refused, 'the refusal must actually have fired, or this proves nothing').toBe(true);
});

test('★ a permanently refused file does not take the rest of the drop with it', async ({ page, baseURL }) => {
  test.setTimeout(180_000);
  await openFileManager(page, baseURL!, 'droppart');

  // 413 is a decision, not a delay — it must NOT be retried, and it must not end the batch.
  let seen = 0;
  await page.route(isUpload, async (route) => {
    if (route.request().method() !== 'POST') return route.fallback();
    seen += 1;
    if (seen === 2) {
      return route.fulfill({ status: 413, headers: { 'content-type': 'application/json' }, body: JSON.stringify({ error: 'file too large' }) });
    }
    return route.fallback();
  });

  await page.getByLabel('Upload files').setInputFiles(files(4));

  // The three good files landed…
  for (const name of ['drop-00.png', 'drop-02.png', 'drop-03.png']) {
    await expect(page.getByText(name)).toBeVisible({ timeout: 60_000 });
  }
  // …and the author is told how many, and WHICH — not just "upload failed".
  await expect(page.getByText(/3 of 4 uploaded — 1 failed \(drop-01\.png\)/)).toBeVisible({ timeout: 30_000 });
});
