import {
  FORM_ID_FIELD,
  HONEYPOT_FIELD,
  TIMETRAP_FIELD,
  HCAPTCHA_RESPONSE_FIELD,
  MIN_SUBMIT_ELAPSED_MS,
  type Form,
} from '@sitewright/schema';

/** Max raw request body the generated PHP accepts before rejecting (defense-in-depth). */
const PHP_MAX_BODY_BYTES = 128 * 1024;
/** Max JSON nesting depth the generated PHP decodes. */
const PHP_JSON_DEPTH = 10;

// Generates `contact.php` for forms whose mode is `contactPhp` (Mode B / PHP
// mail()). The exported PHP runs on the CUSTOMER's own host — no SMTP credentials
// are ever written into it; it relies on the host's local mailer via PHP mail().
// One file handles every contactPhp form, dispatched by the hidden `_form` field.
//
// Security model:
//  - The recipient + subject are baked SERVER-SIDE (in the PHP, not the HTML) as a
//    JSON map, decoded at runtime — so neither reaches the browser, and JSON
//    encoding neutralizes any quote/backslash in the data.
//  - `recipient` is email-validated by FormSchema (no CRLF) → safe as mail() `to`.
//  - `subject` is CRLF-stripped in PHP before use (header-injection guard).
//  - Submitted values go into the mail BODY only (never headers); a submitted
//    `email` becomes Reply-To only after PHP-side email + CRLF validation.
//  - honeypot + time-trap mirror the platform endpoint (silent accept + drop).

interface ContactConfig {
  recipient: string;
  subject: string;
}

/** Escapes a JS string for embedding inside a PHP single-quoted string literal. */
function phpSingleQuote(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/** True if `forms` contains at least one contactPhp form (caller gates on this). */
export function hasContactPhpForm(forms: readonly Form[]): boolean {
  return forms.some((f) => f.mode === 'contactPhp');
}

/**
 * Renders `contact.php`. Only `contactPhp` forms are included; the resolved
 * recipient + subject are baked per form id. Returns the full PHP source.
 */
export function renderContactPhp(forms: readonly Form[]): string {
  const map: Record<string, ContactConfig> = {};
  for (const form of forms) {
    if (form.mode !== 'contactPhp') continue;
    map[form.id] = {
      recipient: form.recipient,
      subject: form.subject || `New "${form.name}" submission`,
    };
  }
  // JSON, then escaped for a PHP single-quoted literal (no PHP interpolation).
  const configLiteral = phpSingleQuote(JSON.stringify(map));

  return `<?php
// Generated by Sitewright — form-to-email via PHP mail(). No credentials stored.
// NOTE: this runs on YOUR host. Bots are filtered by a honeypot + time-trap, but
// for high-traffic sites add web-server rate limiting (e.g. mod_ratelimit / Nginx
// limit_req) in front of this file.
function sw_fail($code) { http_response_code($code); echo json_encode(array('ok' => false)); exit; }

// Public, no-credentials endpoint: permissive CORS (mirrors the platform endpoint).
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: content-type');
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }
header('Content-Type: application/json');
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { sw_fail(405); }

$FORMS = json_decode('${configLiteral}', true);

$raw = file_get_contents('php://input');
if (strlen($raw) > ${PHP_MAX_BODY_BYTES}) { sw_fail(413); }
$data = json_decode($raw, true, ${PHP_JSON_DEPTH});
if (!is_array($data)) { sw_fail(400); }

$formId = isset($data['${FORM_ID_FIELD}']) && is_string($data['${FORM_ID_FIELD}']) ? $data['${FORM_ID_FIELD}'] : '';
if (!isset($FORMS[$formId])) { sw_fail(404); }
$cfg = $FORMS[$formId];

// Honeypot + time-trap: accept silently but drop (don't signal bots).
$hp = isset($data['${HONEYPOT_FIELD}']) && is_string($data['${HONEYPOT_FIELD}']) ? trim($data['${HONEYPOT_FIELD}']) : '';
$elapsed = isset($data['${TIMETRAP_FIELD}']) ? intval($data['${TIMETRAP_FIELD}']) : 0;
if ($hp !== '' || $elapsed < ${MIN_SUBMIT_ELAPSED_MS}) { echo json_encode(array('ok' => true)); exit; }

$skip = array('${HONEYPOT_FIELD}', '${TIMETRAP_FIELD}', '${FORM_ID_FIELD}', '${HCAPTCHA_RESPONSE_FIELD}');
$lines = array();
$replyTo = '';
foreach ($data as $k => $v) {
  if (!is_string($k) || in_array($k, $skip, true)) { continue; }
  if (!is_string($v)) { continue; }
  $lines[] = $k . ":\\n  " . str_replace("\\n", "\\n  ", $v);
  if ($k === 'email' && filter_var($v, FILTER_VALIDATE_EMAIL) && strpbrk($v, "\\r\\n") === false) {
    $replyTo = $v;
  }
}

$to = $cfg['recipient'];
// Strip CR/LF from the subject (header-injection guard).
$subject = str_replace(array("\\r", "\\n"), '', $cfg['subject']);
$body = 'New submission for "' . $formId . "\\"\\n\\n" . implode("\\n\\n", $lines) . "\\n";
$headers = 'Content-Type: text/plain; charset=utf-8';
if ($replyTo !== '') { $headers .= "\\r\\nReply-To: " . $replyTo; }

if (!@mail($to, $subject, $body, $headers)) { sw_fail(502); }
echo json_encode(array('ok' => true));
`;
}
