import type { WebsiteSettings } from '@sitewright/schema';

type Redirect = NonNullable<WebsiteSettings['redirects']>[number];

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** Absolute URL for a published route slug (home → `<base>/`, else `<base>/<slug>/`). */
export function siteUrlFor(siteUrl: string, slug: string | undefined): string {
  const base = siteUrl.replace(/\/+$/, '');
  return slug ? `${base}/${slug}/` : `${base}/`;
}

/** A sitemap.xml from absolute page URLs (callers exclude noindex pages). */
export function renderSitemap(urls: Array<{ loc: string; lastmod?: string }>): string {
  const entries = urls
    .map(
      (u) =>
        `  <url><loc>${xmlEscape(u.loc)}</loc>${u.lastmod ? `<lastmod>${xmlEscape(u.lastmod)}</lastmod>` : ''}</url>`,
    )
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</urlset>\n`;
}

/** robots.txt — allow-all, with the Sitemap line when a sitemap is published. */
export function renderRobots(sitemapUrl?: string): string {
  const lines = ['User-agent: *', 'Allow: /'];
  if (sitemapUrl) lines.push('', `Sitemap: ${sitemapUrl}`);
  return `${lines.join('\n')}\n`;
}

/** Apache `.htaccess` redirect rules (mod_alias). */
export function renderHtaccess(redirects: readonly Redirect[]): string {
  const rules = redirects.map((r) => `  Redirect ${r.status} ${r.from} ${r.to}`).join('\n');
  return `# Generated by Sitewright\n<IfModule mod_alias.c>\n${rules}\n</IfModule>\n`;
}

/** Netlify-style `_redirects` (one rule per line). */
export function renderNetlifyRedirects(redirects: readonly Redirect[]): string {
  return `${redirects.map((r) => `${r.from} ${r.to} ${r.status}`).join('\n')}\n`;
}
