import type { WebsiteSettings } from '@sitewright/schema';

type Redirect = NonNullable<WebsiteSettings['redirects']>[number];

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** Normalized site origin+path with any trailing slash(es) stripped. */
export function siteBase(siteUrl: string): string {
  // Defense-in-depth: drop CR/LF before this value reaches the UNESCAPED sinks it feeds — a newline
  // in `siteUrl` would inject a `robots.txt` directive or break the sitemap `<loc>`. The schema
  // (siteUrlIssue) already rejects all whitespace at the boundary; this guards a non-API DB write.
  return siteUrl.replace(/[\r\n]/g, '').replace(/\/+$/, '');
}

/** Absolute URL for a published route slug (home → `<base>/`, else `<base>/<slug>/`). */
export function siteUrlFor(siteUrl: string, slug: string | undefined): string {
  const base = siteBase(siteUrl);
  return slug ? `${base}/${slug}/` : `${base}/`;
}

/** A sitemap.xml from absolute page URLs (callers exclude noindex pages). */
export function renderSitemap(urls: Array<{ loc: string; lastmod?: string }>): string {
  const entries = urls
    .map(
      (u) =>
        `  <url><loc>${xmlEscape(u.loc)}</loc>${u.lastmod ? `<lastmod>${xmlEscape(u.lastmod)}</lastmod>` : ''}</url>`,
    )
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</urlset>\n`;
}

/** robots.txt — allow-all, with the Sitemap line when a sitemap is published. */
export function renderRobots(sitemapUrl?: string): string {
  const lines = ['User-agent: *', 'Allow: /'];
  if (sitemapUrl) lines.push('', `Sitemap: ${sitemapUrl}`);
  return `${lines.join('\n')}\n`;
}

/** Apache `.htaccess` redirect rules (mod_alias). */
export function renderHtaccess(redirects: readonly Redirect[], opts: { denyFiles?: readonly string[] } = {}): string {
  const parts: string[] = ['# Generated by Sitewright'];
  // Deny direct access to sensitive generated files (today: the contact.php SMTP credentials).
  // Apache-only and therefore BELT-AND-BRACES, never the primary defence — nginx ignores
  // .htaccess entirely, and the file carries its own PHP-level guard for exactly that reason.
  for (const file of opts.denyFiles ?? []) {
    parts.push(
      `<Files "${file}">`,
      '  <IfModule mod_authz_core.c>',
      '    Require all denied',
      '  </IfModule>',
      '  <IfModule !mod_authz_core.c>',
      '    Order allow,deny',
      '    Deny from all',
      '  </IfModule>',
      '</Files>',
    );
  }
  if (redirects.length > 0) {
    const rules = redirects.map((r) => `  Redirect ${r.status} ${r.from} ${r.to}`).join('\n');
    parts.push('<IfModule mod_alias.c>', rules, '</IfModule>');
  }
  return `${parts.join('\n')}\n`;
}

/** Netlify-style `_redirects` (one rule per line). */
export function renderNetlifyRedirects(redirects: readonly Redirect[]): string {
  return `${redirects.map((r) => `${r.from} ${r.to} ${r.status}`).join('\n')}\n`;
}
