import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { ProjectBundle } from '@sitewright/core';
import { buildSite } from '../src/publish/build.js';
import {
  renderSitemap,
  renderRobots,
  renderHtaccess,
  renderNetlifyRedirects,
  siteUrlFor,
} from '../src/publish/seo.js';

describe('seo renderers', () => {
  it('siteUrlFor builds trailing-slash URLs (home → base/)', () => {
    expect(siteUrlFor('https://acme.com/', undefined)).toBe('https://acme.com/');
    expect(siteUrlFor('https://acme.com', 'about')).toBe('https://acme.com/about/');
    expect(siteUrlFor('https://acme.com', 'de/about')).toBe('https://acme.com/de/about/');
  });

  it('renders a sitemap with escaped locs', () => {
    const xml = renderSitemap([{ loc: 'https://acme.com/a&b/', lastmod: '2026-05-31' }]);
    expect(xml).toContain('<loc>https://acme.com/a&amp;b/</loc>');
    expect(xml).toContain('<lastmod>2026-05-31</lastmod>');
    expect(xml).toMatch(/^<\?xml/);
  });

  it('renders robots with and without the Sitemap line', () => {
    expect(renderRobots()).toBe('User-agent: *\nAllow: /\n');
    expect(renderRobots('https://acme.com/sitemap.xml')).toContain('Sitemap: https://acme.com/sitemap.xml');
  });

  it('renders Apache + Netlify redirect rules', () => {
    const rules = [{ from: '/old', to: '/new', status: 301 as const }];
    expect(renderHtaccess(rules)).toContain('Redirect 301 /old /new');
    expect(renderNetlifyRedirects(rules)).toBe('/old /new 301\n');
  });

  it('renderHtaccess with no rules emits no IfModule block', () => {
    expect(renderHtaccess([])).toBe('# Generated by Sitewright\n');
  });
});

function bundle(over: Partial<ProjectBundle> = {}): ProjectBundle {
  return {
    project: {
      formatVersion: 2 as const,
      id: 'p',
      name: 'Acme',
      slug: 'acme',
      identity: { name: 'Acme', colors: { primary: '#0a7' } },
      settings: { defaultLocale: 'en', locales: ['en'] },
    },
    pages: [],
    partials: [],
    datasets: [],
    entries: [],
    ...over,
  } as ProjectBundle;
}

describe('buildSite — SEO output', () => {
  let outDir: string;
  beforeEach(async () => {
    outDir = await mkdtemp(join(tmpdir(), 'sw-seo-'));
  });
  afterEach(async () => {
    await rm(outDir, { recursive: true, force: true });
  });

  const pages = [
    { id: 'home', path: '', title: 'Home', root: { id: 'r1', type: 'Section' } },
    { id: 'about', path: 'about', title: 'About', root: { id: 'r2', type: 'Section' } },
    { id: 'secret', path: 'secret', title: 'Secret', noindex: true, root: { id: 'r3', type: 'Section' } },
  ];

  it('emits sitemap.xml (excluding noindex), a robots.txt with the Sitemap line, and redirect files', async () => {
    await buildSite({
      publishedAt: '2026-05-31T00:00:00.000Z',
      outDir,
      bundle: bundle({
        pages,
        project: {
          ...bundle().project,
          website: { siteUrl: 'https://acme.com', redirects: [{ from: '/old', to: '/new', status: 301 }] },
        } as ProjectBundle['project'],
      }),
    });
    const sitemap = await readFile(join(outDir, 'sitemap.xml'), 'utf8');
    expect(sitemap).toContain('<loc>https://acme.com/</loc>');
    expect(sitemap).toContain('<loc>https://acme.com/about/</loc>');
    expect(sitemap).not.toContain('/secret/'); // noindex excluded
    // lastmod is a date (YYYY-MM-DD), not a full ISO datetime.
    expect(sitemap).toContain('<lastmod>2026-05-31</lastmod>');
    expect(sitemap).not.toContain('2026-05-31T');
    const robots = await readFile(join(outDir, 'robots.txt'), 'utf8');
    expect(robots).toContain('Sitemap: https://acme.com/sitemap.xml');
    expect(await readFile(join(outDir, '.htaccess'), 'utf8')).toContain('Redirect 301 /old /new');
    expect(await readFile(join(outDir, '_redirects'), 'utf8')).toContain('/old /new 301');
  });

  it('writes a plain robots.txt and no sitemap when no siteUrl is configured', async () => {
    await buildSite({ publishedAt: '2026-05-31T00:00:00.000Z', outDir, bundle: bundle({ pages }) });
    const robots = await readFile(join(outDir, 'robots.txt'), 'utf8');
    expect(robots).toBe('User-agent: *\nAllow: /\n');
    await expect(readFile(join(outDir, 'sitemap.xml'), 'utf8')).rejects.toThrow();
  });
});
