import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { ProjectBundle } from '@sitewright/core';
import { buildSite } from '../src/publish/build.js';
import {
  renderSitemap,
  renderRobots,
  renderHtaccess,
  renderNetlifyRedirects,
  siteUrlFor,
  siteBase,
  renderSecurityTxt,
  securityTxtExpires,
  securityTxtContacts,
  telUri,
  SECURITY_TXT_PATH,
} from '../src/publish/seo.js';

describe('seo renderers', () => {
  it('siteUrlFor builds trailing-slash URLs (home → base/)', () => {
    expect(siteUrlFor('https://acme.com/', undefined)).toBe('https://acme.com/');
    expect(siteUrlFor('https://acme.com', 'about')).toBe('https://acme.com/about/');
    expect(siteUrlFor('https://acme.com', 'de/about')).toBe('https://acme.com/de/about/');
  });

  it('siteBase strips CR/LF (defense-in-depth against robots.txt/sitemap injection)', () => {
    // The schema rejects whitespace at the boundary; this guards a non-API DB write from smuggling
    // a newline into the UNESCAPED robots.txt "Sitemap:" line or a sitemap <loc>.
    expect(siteBase('https://acme.com\nDisallow: x')).toBe('https://acme.comDisallow: x');
    expect(siteBase('https://acme.com\r\n')).toBe('https://acme.com');
    // With the newline stripped, the robots.txt Sitemap line stays ONE line — no injected directive.
    expect(renderRobots(`${siteBase('https://acme.com\nDisallow: /')}/sitemap.xml`)).not.toContain('\nDisallow');
    expect(siteBase('https://acme.com/')).toBe('https://acme.com'); // still strips the trailing slash
  });

  it('renders a sitemap with escaped locs', () => {
    const xml = renderSitemap([{ loc: 'https://acme.com/a&b/', lastmod: '2026-05-31' }]);
    expect(xml).toContain('<loc>https://acme.com/a&amp;b/</loc>');
    expect(xml).toContain('<lastmod>2026-05-31</lastmod>');
    expect(xml).toMatch(/^<\?xml/);
  });

  it('renders robots with and without the Sitemap line', () => {
    expect(renderRobots()).toBe('User-agent: *\nAllow: /\n');
    expect(renderRobots('https://acme.com/sitemap.xml')).toContain('Sitemap: https://acme.com/sitemap.xml');
  });

  it('renders Apache + Netlify redirect rules', () => {
    const rules = [{ from: '/old', to: '/new', status: 301 as const }];
    expect(renderHtaccess(rules)).toContain('Redirect 301 /old /new');
    expect(renderNetlifyRedirects(rules)).toBe('/old /new 301\n');
  });

  it('renderHtaccess with no rules emits no IfModule block', () => {
    expect(renderHtaccess([])).toBe('# Generated by Sitewright\n');
  });
});

describe('security.txt (RFC 9116)', () => {
  it('publishes to the normative /.well-known path', () => {
    expect(SECURITY_TXT_PATH).toBe('.well-known/security.txt');
  });

  it('renders the required fields, in preference order, ending with a newline', () => {
    const txt = renderSecurityTxt({
      contacts: ['https://acme.com/contact/', 'tel:+14155550123'],
      expires: '2031-05-31T00:00:00Z',
      canonical: 'https://acme.com/.well-known/security.txt',
      policy: 'https://acme.com/security-policy/',
      acknowledgments: 'https://acme.com/hall-of-fame/',
      preferredLanguages: 'en',
    });
    expect(txt).toBe(
      '# Security contact information for this site — https://www.rfc-editor.org/info/rfc9116\n' +
        'Contact: https://acme.com/contact/\n' +
        'Contact: tel:+14155550123\n' +
        'Expires: 2031-05-31T00:00:00Z\n' +
        'Preferred-Languages: en\n' +
        'Canonical: https://acme.com/.well-known/security.txt\n' +
        'Policy: https://acme.com/security-policy/\n' +
        'Acknowledgments: https://acme.com/hall-of-fame/\n',
    );
    // Exactly one Expires and at most one Preferred-Languages — both normative.
    expect(txt.match(/^Expires:/gm)).toHaveLength(1);
    expect(txt.match(/^Preferred-Languages:/gm)).toHaveLength(1);
  });

  it('omits every optional field that is unset', () => {
    expect(renderSecurityTxt({ contacts: ['mailto:security@acme.com'], expires: '2031-05-31T00:00:00Z' })).toBe(
      '# Security contact information for this site — https://www.rfc-editor.org/info/rfc9116\n' +
        'Contact: mailto:security@acme.com\n' +
        'Expires: 2031-05-31T00:00:00Z\n',
    );
  });

  it('strips CR/LF from every value so a stored newline cannot inject a field', () => {
    const txt = renderSecurityTxt({
      contacts: ['https://acme.com/contact/\nContact: mailto:evil@example.com'],
      expires: '2031-05-31T00:00:00Z\nPolicy: https://evil.example.com/',
      canonical: 'https://acme.com/\r\nAcknowledgments: https://evil.example.com/',
    });
    // The smuggled text survives as inert tail on its own line's VALUE — it never becomes a field.
    expect(txt).not.toMatch(/^Contact: mailto:evil/m);
    expect(txt).not.toMatch(/^Policy:/m);
    expect(txt).not.toMatch(/^Acknowledgments:/m);
    // One Contact, one Expires, one Canonical — the injected text is inert on its own line's tail.
    expect(txt.match(/^Contact:/gm)).toHaveLength(1);
    expect(txt.match(/^Expires:/gm)).toHaveLength(1);
    expect(txt.match(/^Canonical:/gm)).toHaveLength(1);
  });

  it('securityTxtExpires is RFC 3339 UTC, N years out, to the second', () => {
    expect(securityTxtExpires(new Date('2026-05-31T12:34:56.789Z'), 5)).toBe('2031-05-31T12:34:56Z');
    expect(securityTxtExpires(new Date('2026-05-31T12:34:56.789Z'), 1)).toBe('2027-05-31T12:34:56Z');
    // Feb 29 in a non-leap target year normalizes forward rather than producing an invalid date.
    expect(securityTxtExpires(new Date('2028-02-29T00:00:00Z'), 1)).toBe('2029-03-01T00:00:00Z');
    // The value parses back as a real date (what a validator will do to it).
    expect(new Date(securityTxtExpires(new Date('2026-05-31T00:00:00Z'), 2)).getUTCFullYear()).toBe(2028);
  });

  it('telUri accepts E.164 (and the 00 international prefix) but never invents a country code', () => {
    expect(telUri('+14155550123')).toBe('tel:+14155550123');
    expect(telUri('+49 (0)30 1234-567')).toBe('tel:+49301234567');
    expect(telUri('0049 30 1234567')).toBe('tel:+49301234567'); // the 00 access prefix becomes +
    expect(telUri('030 1234567')).toBeNull(); // national, no country code → not publishable
    expect(telUri('call us')).toBeNull();
    expect(telUri('')).toBeNull();
  });

  it('securityTxtContacts orders page → phone → email and names what did not resolve', () => {
    expect(
      securityTxtContacts({ contactPageUrl: 'https://acme.com/contact/', telephone: '+14155550123', email: 'hi@acme.com' }),
    ).toEqual({
      contacts: ['https://acme.com/contact/', 'tel:+14155550123', 'mailto:hi@acme.com'],
      unresolved: [],
    });
    // Unselected sources are simply absent — not reported as unresolved.
    expect(securityTxtContacts({ email: 'hi@acme.com' })).toEqual({
      contacts: ['mailto:hi@acme.com'],
      unresolved: [],
    });
    expect(securityTxtContacts({})).toEqual({ contacts: [], unresolved: [] });
    // Selected but unusable → reported by name, so the publish error can say which one.
    expect(securityTxtContacts({ contactPageUrl: null, telephone: '030 123', email: null })).toEqual({
      contacts: [],
      unresolved: ['page', 'phone', 'email'],
    });
  });
});

function bundle(over: Partial<ProjectBundle> = {}): ProjectBundle {
  return {
    project: {
      formatVersion: 2 as const,
      id: 'p',
      name: 'Acme',
      slug: 'acme',
      identity: { name: 'Acme', colors: { primary: '#0a7' } },
      settings: { defaultLocale: 'en', locales: ['en'] },
    },
    pages: [],
    datasets: [],
    entries: [],
    ...over,
  } as ProjectBundle;
}

describe('buildSite — SEO output', () => {
  let outDir: string;
  beforeEach(async () => {
    outDir = await mkdtemp(join(tmpdir(), 'sw-seo-'));
  });
  afterEach(async () => {
    await rm(outDir, { recursive: true, force: true });
  });

  const pages = [
    { id: 'home', path: '', title: 'Home', root: { id: 'r1', type: 'Section' } },
    { id: 'about', path: 'about', title: 'About', root: { id: 'r2', type: 'Section' } },
    { id: 'secret', path: 'secret', title: 'Secret', noindex: true, root: { id: 'r3', type: 'Section' } },
  ];

  it('emits sitemap.xml (excluding noindex), a robots.txt with the Sitemap line, and redirect files', async () => {
    await buildSite({
      publishedAt: '2026-05-31T00:00:00.000Z',
      outDir,
      bundle: bundle({
        pages,
        project: {
          ...bundle().project,
          website: { siteUrl: 'https://acme.com', redirects: [{ from: '/old', to: '/new', status: 301 }] },
        } as ProjectBundle['project'],
      }),
    });
    const sitemap = await readFile(join(outDir, 'sitemap.xml'), 'utf8');
    expect(sitemap).toContain('<loc>https://acme.com/</loc>');
    expect(sitemap).toContain('<loc>https://acme.com/about/</loc>');
    expect(sitemap).not.toContain('/secret/'); // noindex excluded
    // lastmod is a date (YYYY-MM-DD), not a full ISO datetime.
    expect(sitemap).toContain('<lastmod>2026-05-31</lastmod>');
    expect(sitemap).not.toContain('2026-05-31T');
    const robots = await readFile(join(outDir, 'robots.txt'), 'utf8');
    expect(robots).toContain('Sitemap: https://acme.com/sitemap.xml');
    expect(await readFile(join(outDir, '.htaccess'), 'utf8')).toContain('Redirect 301 /old /new');
    expect(await readFile(join(outDir, '_redirects'), 'utf8')).toContain('/old /new 301');
  });

  it('writes a plain robots.txt and no sitemap when no siteUrl is configured', async () => {
    await buildSite({ publishedAt: '2026-05-31T00:00:00.000Z', outDir, bundle: bundle({ pages }) });
    const robots = await readFile(join(outDir, 'robots.txt'), 'utf8');
    expect(robots).toBe('User-agent: *\nAllow: /\n');
    await expect(readFile(join(outDir, 'sitemap.xml'), 'utf8')).rejects.toThrow();
  });
});

describe('buildSite — security.txt', () => {
  let outDir: string;
  beforeEach(async () => {
    outDir = await mkdtemp(join(tmpdir(), 'sw-sectxt-'));
  });
  afterEach(async () => {
    await rm(outDir, { recursive: true, force: true });
  });

  const pages = [
    { id: 'home', path: '', title: 'Home', root: { id: 'r1', type: 'Section' } },
    { id: 'contact', path: 'contact', title: 'Contact', root: { id: 'r2', type: 'Section' } },
  ];

  /** A bundle whose project carries the given website settings + identity contact details. */
  const withSecurity = (
    website: Record<string, unknown>,
    identity: Record<string, unknown> = {},
  ): ProjectBundle =>
    bundle({
      pages,
      project: {
        ...bundle().project,
        identity: { name: 'Acme', colors: { primary: '#0a7' }, ...identity },
        website,
      } as ProjectBundle['project'],
    });

  const read = (): Promise<string> => readFile(join(outDir, '.well-known', 'security.txt'), 'utf8');

  it('emits nothing unless the author opts in', async () => {
    await buildSite({ publishedAt: '2026-05-31T00:00:00.000Z', outDir, bundle: bundle({ pages }) });
    await expect(read()).rejects.toThrow();
  });

  it('publishes the contact page URL, a rolling Expires, Canonical and the site languages', async () => {
    await buildSite({
      publishedAt: '2026-05-31T00:00:00.000Z',
      outDir,
      bundle: withSecurity({
        siteUrl: 'https://acme.com',
        security: { enabled: true, contactPageId: 'contact', policyUrl: 'https://acme.com/policy/' },
      }),
    });
    const txt = await read();
    expect(txt).toContain('Contact: https://acme.com/contact/');
    // expiryYears unset → the 5-year default, measured from THIS publish.
    expect(txt).toContain('Expires: 2031-05-31T00:00:00Z');
    expect(txt).toContain('Canonical: https://acme.com/.well-known/security.txt');
    expect(txt).toContain('Policy: https://acme.com/policy/');
    expect(txt).toContain('Preferred-Languages: en');
    // Email is never emitted unless explicitly selected — the file is public and harvested.
    expect(txt).not.toContain('mailto:');
  });

  it('honours the chosen expiry window', async () => {
    await buildSite({
      publishedAt: '2026-05-31T00:00:00.000Z',
      outDir,
      bundle: withSecurity({ siteUrl: 'https://acme.com', security: { enabled: true, contactPageId: 'contact', expiryYears: 1 } }),
    });
    expect(await read()).toContain('Expires: 2027-05-31T00:00:00Z');
  });

  it('orders page → phone → email and converts identity values to URIs', async () => {
    await buildSite({
      publishedAt: '2026-05-31T00:00:00.000Z',
      outDir,
      bundle: withSecurity(
        {
          siteUrl: 'https://acme.com',
          security: { enabled: true, contactPageId: 'contact', usePhone: true, useEmail: true },
        },
        { telephone: '+49 (0)30 1234567', email: 'hello@acme.com' },
      ),
    });
    const contacts = (await read()).split('\n').filter((l) => l.startsWith('Contact:'));
    expect(contacts).toEqual([
      'Contact: https://acme.com/contact/',
      'Contact: tel:+49301234567',
      'Contact: mailto:hello@acme.com',
    ]);
  });

  it('works with no siteUrl when the contacts do not need one (no Canonical emitted)', async () => {
    await buildSite({
      publishedAt: '2026-05-31T00:00:00.000Z',
      outDir,
      bundle: withSecurity({ security: { enabled: true, useEmail: true } }, { email: 'hello@acme.com' }),
    });
    const txt = await read();
    expect(txt).toContain('Contact: mailto:hello@acme.com');
    expect(txt).not.toContain('Canonical:');
  });

  it('never blanks the DRAFT PREVIEW over a misconfigured contact — it skips the file instead', async () => {
    // The always-on whole-site preview must not go down because of one unrelated setting (the same
    // reason a broken page renders an error document there rather than aborting the build).
    await expect(
      buildSite({
        publishedAt: '2026-05-31T00:00:00.000Z',
        outDir,
        previewRuntime: 'window.__SW_PREVIEW__=1;',
        bundle: withSecurity({ security: { enabled: true, useEmail: true, usePhone: true } }),
      }),
    ).resolves.toBeTruthy();
    // …and no Contact-less file is left behind — that would be invalid per RFC 9116 §2.5.3.
    await expect(read()).rejects.toThrow();
  });

  it('still emits in preview when the contacts DO resolve', async () => {
    await buildSite({
      publishedAt: '2026-05-31T00:00:00.000Z',
      outDir,
      previewRuntime: 'window.__SW_PREVIEW__=1;',
      bundle: withSecurity({ security: { enabled: true, useEmail: true } }, { email: 'hello@acme.com' }),
    });
    expect(await read()).toContain('Contact: mailto:hello@acme.com');
  });

  it('FAILS the publish when a selected contact source resolves to nothing, naming the source', async () => {
    // A contact page that is not in this publish.
    await expect(
      buildSite({
        publishedAt: '2026-05-31T00:00:00.000Z',
        outDir,
        bundle: withSecurity({ siteUrl: 'https://acme.com', security: { enabled: true, contactPageId: 'gone' } }),
      }),
    ).rejects.toThrow(/not in this publish/);

    // A contact page with no Site URL to make it absolute.
    await expect(
      buildSite({
        publishedAt: '2026-05-31T00:00:00.000Z',
        outDir,
        bundle: withSecurity({ security: { enabled: true, contactPageId: 'contact' } }),
      }),
    ).rejects.toThrow(/needs a Site URL/);

    // A phone number with no country code — not expressible as a tel: URI.
    await expect(
      buildSite({
        publishedAt: '2026-05-31T00:00:00.000Z',
        outDir,
        bundle: withSecurity({ security: { enabled: true, usePhone: true } }, { telephone: '030 1234567' }),
      }),
    ).rejects.toThrow(/no country code/);

    // Selected sources the Corporate Identity simply doesn't carry.
    await expect(
      buildSite({
        publishedAt: '2026-05-31T00:00:00.000Z',
        outDir,
        bundle: withSecurity({ security: { enabled: true, useEmail: true, usePhone: true } }),
      }),
    ).rejects.toThrow(/phone number is not set.*email address is not set/s);
  });
});
