#!/usr/bin/env node
// Bundles the vendor-src/*.entry.js component runtimes (first-party wiring + the MIT libraries
// they import) into checked-in src/vendor/*-runtime.ts modules, the same generate-and-check-in
// discipline as gen-brand-icons/gen-lucide-icons: reproducible builds, no build-time network,
// auditable diffs on upgrades. CI runs `gen:vendor:check` (regenerate + git diff --exit-code).
//
// Each generated module exports the bundled, minified runtime as a STRING constant that
// components.ts ships through the regular only-used-ships pipeline (same-origin components.js,
// CSP `default-src 'self'` — no CDN, no eval). A license banner with every bundled package's
// name@version (all MIT) is embedded in the shipped JS itself.
import { build } from 'esbuild';
import { mkdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
// Resolves a (possibly transitive) dependency's package.json through Node's resolver — pnpm
// only exposes transitive deps (wheel-gestures) via the dependent package's own node_modules.
const requireFrom = (fromDir) => createRequire(join(fromDir, 'noop.js'));
function resolvePkgJson(name) {
  // Resolve the package's ENTRY (always exported), then cut back to its root dir — `exports`
  // maps routinely omit "./package.json", so it can't be resolved directly.
  const marker = join('node_modules', ...name.split('/'));
  // Second dir: `wheel-gestures` is a TRANSITIVE dep only reachable through its parent
  // `embla-carousel-wheel-gestures` under pnpm's isolated layout. If that package is ever
  // bumped to a version that inlines or drops wheel-gestures, update the libs list + this path.
  for (const dir of [pkgRoot, join(pkgRoot, 'node_modules', 'embla-carousel-wheel-gestures')]) {
    let entry;
    try {
      // realpath first: transitive deps are only visible from the package's REAL (.pnpm)
      // location — createRequire on the symlinked path can't see its siblings.
      entry = requireFrom(realpathSync(dir)).resolve(name);
    } catch {
      continue;
    }
    const i = entry.lastIndexOf(marker);
    if (i !== -1) return join(entry.slice(0, i + marker.length), 'package.json');
  }
  throw new Error(`gen-vendor: cannot locate package.json for "${name}"`);
}

const TARGETS = [
  {
    entry: 'vendor-src/carousel.entry.js',
    out: 'src/vendor/carousel-runtime.ts',
    jsConst: 'CAROUSEL_RUNTIME_JS',
    libs: [
      'embla-carousel',
      'embla-carousel-autoplay',
      'embla-carousel-auto-scroll',
      'embla-carousel-auto-height',
      'embla-carousel-fade',
      'embla-carousel-wheel-gestures',
      'wheel-gestures',
    ],
  },
  {
    entry: 'vendor-src/lightbox.entry.js',
    out: 'src/vendor/lightbox-runtime.ts',
    jsConst: 'LIGHTBOX_RUNTIME_JS',
    libs: ['glightbox'],
    css: { from: 'node_modules/glightbox/dist/css/glightbox.min.css', cssConst: 'LIGHTBOX_VENDOR_CSS' },
  },
];

function libBanner(libs) {
  const lines = libs.map((name) => {
    const pkg = JSON.parse(readFileSync(resolvePkgJson(name), 'utf8'));
    // Hard gate: these bundles ship on customer sites, so every vendored package MUST be MIT.
    // A dep that relicenses (the easepick/Flickity trap) fails generation, not human review.
    if (pkg.license !== 'MIT') {
      throw new Error(`gen-vendor: ${pkg.name}@${pkg.version} is licensed "${pkg.license}" — only MIT may be vendored`);
    }
    return `${pkg.name}@${pkg.version} (${pkg.license})`;
  });
  return `/*! Sitewright component runtime. Bundles: ${lines.join(', ')}. See each package for its MIT license text. */`;
}

for (const t of TARGETS) {
  const banner = libBanner(t.libs);
  const result = await build({
    entryPoints: [join(pkgRoot, t.entry)],
    bundle: true,
    minify: true,
    format: 'iife',
    target: 'es2018',
    write: false,
    banner: { js: banner },
    legalComments: 'none',
  });
  const js = result.outputFiles[0].text.trimEnd();

  const parts = [
    '// AUTO-GENERATED by scripts/gen-vendor.mjs — DO NOT EDIT BY HAND.',
    `// Bundled from ${t.entry} + ${t.libs.join(', ')} (all MIT; banner embedded in the JS).`,
    '// Regenerate: pnpm --filter @sitewright/blocks gen:vendor',
    '',
    `export const ${t.jsConst}: string = ${JSON.stringify(js)};`,
  ];
  if (t.css) {
    const css = readFileSync(join(pkgRoot, t.css.from), 'utf8').trim();
    parts.push('', `export const ${t.css.cssConst}: string = ${JSON.stringify(css)};`);
  }
  parts.push('');

  const outPath = join(pkgRoot, t.out);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, parts.join('\n'), 'utf8');
  const kb = (Buffer.byteLength(js) / 1024).toFixed(1);
  process.stderr.write(`gen-vendor: wrote ${t.out} (js ${kb} KB${t.css ? ' + vendor css' : ''})\n`);
}
