import { chromium } from '@playwright/test';
const [url, out] = process.argv.slice(2);
const b = await chromium.launch({ args: ['--no-sandbox'] });
const ctx = await b.newContext({ viewport: { width: 1440, height: 300 } });
const pg = await ctx.newPage();
await pg.goto(url, { waitUntil: 'networkidle', timeout: 60000 }).catch(()=>{});
await pg.evaluate(async () => { await (document.fonts ? document.fonts.ready : Promise.resolve()); });
await pg.waitForTimeout(800);
await pg.screenshot({ path: out, clip: { x: 120, y: 0, width: 900, height: 120 }, quality: 90, type: 'jpeg' });
console.log('brand shot saved');
await b.close();
