import { chromium } from '@playwright/test';
const [file, out] = process.argv.slice(2);
const b = await chromium.launch({ args: ['--no-sandbox'] });
const pg = await b.newPage({ viewport: { width: 800, height: 200 } });
await pg.goto('file://' + file, { waitUntil: 'networkidle', timeout: 30000 }).catch(e=>console.log('nav',e.message));
await pg.evaluate(async () => { await document.fonts.ready; });
await pg.waitForTimeout(800);
const ok = await pg.evaluate(() => document.fonts.check('30px "test-corsiva"'));
console.log('test-corsiva loaded from media URL:', ok);
await pg.screenshot({ path: out, quality: 92, type: 'jpeg' });
await b.close();
